const CAPITULO = {
  numero: "8.5",
  titulo: "El Nacimiento del Futuro",
  paginas: "68-75",
  nav: {
    anterior: { href: "capitulo_08.html", label: "← Capítulo 8" },
    siguiente: { href: "capitulo_09.html", label: "Capítulo 9 →" }
  },
  contenido: [
    "[P68]",
    "[LOC]Hospital Central de Seúl - Sala de Maternidad Especial - 03:17 hrs",
    "[OPEN]El Dr. Kim Jae-sung había asistido a más de dos mil partos en su carrera de veinte años, pero nunca había visto un feto que pareciera estar dirigiendo su propio nacimiento.",
    "Sophie Yun llevaba cuarenta y dos horas en trabajo de parto. Pero no era labor de parto en ningún sentido médico tradicional.",
    "No había contracciones violentas ni gritos de dolor. Había una especie de negociación.",
    "Su bebé se movía en patrones específicos, reorganizando no solo su posición sino la estructura misma del útero para facilitar un tipo de nacimiento que la medicina humana nunca había documentado.",
    "—Doctor, necesito que entienda algo,",
    "Sophie habló con una calma que a él le resultaba más difícil de sostener que el pánico. Sus ojos estaban fijos en el techo pero claramente viendo algo que él no podía percibir.",
    "—Mi hijo no va a nacer de la manera normal. Va a emerger.",
    "Los monitores fetales mostraban patrones que desafiaban la fisiología conocida. El ritmo cardíaco del bebé no era aleatorio: seguía secuencias matemáticas complejas. Cada latido era una ecuación. Los movimientos no eran los de un feto tratando de posicionarse para el nacimiento, sino los de alguien que construía algo desde adentro.",
    "[P69]",
    "La Dra. Jennifer Park, la médica militar asignada como enlace, había estado monitoreando los signos vitales de Sophie desde que llegó al hospital. Lo que veía en los datos la llenaba tanto de terror como de asombro.",
    "—Dr. Kim, mire esto,",
    "susurró, mostrándole las lecturas de actividad cerebral de Sophie.",
    "—Su cerebro muestra patrones de actividad que normalmente veríamos en dos personas distintas. Como si estuviera teniendo una conversación.",
    "—¿Con quién?",
    "—Con su hijo. No telepáticamente. Es más fundamental. Comparten el mismo sistema nervioso, pero mantienen personalidades separadas.",
    "Sophie se incorporó en la cama. Por un momento sus ojos brillaron con la misma luz dorada que habían visto en los convertidos del valle.",
    "—Es hora,",
    "dijo. Su voz tenía armónicos que no venían completamente de su garganta.",
    "[P70]",
    "El proceso que siguió no podía llamarse parto en ningún sentido tradicional.",
    "La piel del abdomen de Sophie comenzó a brillar desde adentro. Una fuente de luz suave pero constante en su interior.",
    "No había dolor. Había algo que se parecía a una transformación mutua entre madre e hijo.",
    "En lugar de contracciones, el útero de Sophie parecía estar abriéndose. No físicamente, sino en otra dimensión de lo físico. El Dr. Kim podía ver —y esto lo atormentaría durante el resto de su vida— espacios que no deberían haber existido dentro del cuerpo humano. Cámaras más grandes por dentro que por fuera. Geometrías que hacían que su mente se esforzara por no procesar lo que estaba procesando.",
    "—Esto no es médicamente posible,",
    "murmuró el Dr. Kim. Sus manos seguían trabajando, obedeciendo décadas de instinto médico mientras su mente se desconectaba de lo que veían sus ojos.",
    "[P71]",
    "Cuando el bebé emergió, no lloró.",
    "Emitió un sonido que los tres recordarían de manera distinta: la Dra. Park diría después que era una frecuencia. El Dr. Kim diría que fue silencio con peso. Sophie no lo describiría. Simplemente cerraría los ojos cada vez que alguien le preguntara.",
    "Luego el bebé se quedó en silencio.",
    "Era físicamente un recién nacido humano normal: diez dedos en las manos, diez en los pies, peso y longitud dentro de rangos normales. Pero cuando abrió los ojos, no miró al Dr. Kim. No miró a la Dra. Park. Miró directamente a Sophie, con una fijeza que ningún recién nacido debería poder sostener.",
    "Sophie no dijo nada durante un momento largo.",
    "Luego habló, y su voz era completamente suya —no tenía armónicos, no brillaba— pero lo que dijo no venía de ningún lugar que ella pudiera señalar:",
    "—Los devoradores llegan en menos de dos años.",
    "Pausa.",
    "—No sé cómo lo sé.",
    "La Dra. Park levantó la tableta. Sus dedos temblaron un segundo antes de tocar la pantalla.",
    "—¿Devoradores?",
    "—Hay lugares seguros. Espacios fuera del tiempo normal. Para los que no se van a transformar. Para los que eligen quedarse.",
    "—¿Quién los preparó?",
    "Sophie no respondió esa pregunta. Extendió los brazos.",
    "El Dr. Kim le entregó al bebé.",
    "[P72]",
    "Sophie lo sostuvo contra su pecho. El bebé tenía los ojos abiertos todavía, mirándola con esa fijeza que no correspondía a ningún manual pediátrico.",
    "—Los 2,847 descendientes tienen que elegir. No pueden elegir si no saben que tienen la opción. Alguien tiene que decírselo antes de que lleguen los devoradores.",
    "El Dr. Kim observaba el monitor de signos vitales del bebé. Los patrones que aparecían en pantalla no se parecían a nada en su base de datos. Tomó una foto. Luego tomó otra. Luego bajó el teléfono porque entendió que no importaba cuántas fotos tomara.",
    "Sophie miraba a su hijo.",
    "—¿Cómo voy a ser tu madre si ni siquiera recuerdo haber decidido tenerte? Ni siquiera recuerdo... Dios mío.",
    "El bebé no dijo nada.",
    "Sophie continuó:",
    "—¿Y si no soy una buena madre para alguien como tú?",
    "El bebé abrió la boca. Lo que salió fue una voz pequeña, clara, sin armónicos. Una voz de recién nacido que no debería existir.",
    "—No sé qué es eso. El amor de una madre. Nunca lo he tenido.",
    "Pausa breve.",
    "—Necesito que me lo enseñes.",
    "La Dra. Park dejó de escribir.",
    "El Dr. Kim se sentó en la silla detrás de él. No lo hizo con elegancia: se dejó caer hacia atrás hasta encontrar el asiento, los ojos todavía en el monitor.",
    "[P73]",
    "Sophie no respondió al bebé de inmediato. Lo sostuvo. Lo miró. Pasó un dedo por la curva de su cráneo.",
    "Afuera, en los pasillos, el hospital seguía con su ritmo de las tres de la madrugada. Pasos. Una camilla. El sonido lejano de una alarma que alguien apagó.",
    "Nada afuera sabía lo que acababa de ocurrir adentro.",
    "—Los santuarios temporales están listos. Cuando lleguen los devoradores, las personas que elijan quedarse humanas van a necesitar saber adónde ir. Esa información existe. Alguien la tiene que distribuir.",
    "—¿Cómo sabe eso?",
    "preguntó la Dra. Park.",
    "—No lo sé.",
    "Silencio.",
    "—Pero lo sé.",
    "El Dr. Kim había estado tomando notas. Se detuvo cuando se dio cuenta de que su bolígrafo estaba escribiendo símbolos que no reconocía. Los miró durante varios segundos. Cerró el bloc.",
    "La Dra. Park se acercó a la ventana y miró hacia la ciudad de Seúl. Las luces de la ciudad parecían diferentes. No sabría explicar por qué.",
    "[P74]",
    "Sophie alimentó a su hijo en silencio durante varios minutos. El bebé lo aceptó con la seriedad de alguien que sabe que esto también es necesario.",
    "La Dra. Park revisaba sus anotaciones. Había cuatro páginas llenas de información que Sophie había dado sin levantar la vista de su hijo. Información que la Dra. Park no sabía de dónde venía y que tampoco sabía cómo verificar, pero que tenía la cadencia de algo verdadero: específico, sin adornos, sin vacilaciones.",
    "El Dr. Kim salió al pasillo. Se sentó en el suelo con la espalda contra la pared, a dos metros de la puerta cerrada, y se quedó mirando el techo del corredor durante un tiempo que no midió.",
    "Adentro, Sophie habló de nuevo:",
    "—Tengo que asegurarme de que cuando llegue el momento de esa elección, las personas tengan la información que necesitan. No la elección que yo haría. La información para que elijan ellas.",
    "El bebé seguía alimentándose. No respondió.",
    "Afuera, en el pasillo, el teléfono del Dr. Kim vibró. Lo miró desde el suelo. Era una llamada del General Kim.",
    "Se puso de pie. Entró a la habitación.",
    "—El General quiere que vengan al Centro de Comando. Hay situaciones desarrollándose en todo el mundo que parecen estar coordinadas con... con esta noche.",
    "Sophie miró a su hijo. El bebé había terminado de alimentarse y tenía los ojos abiertos de nuevo.",
    "—Dígale que vamos.",
    "[P75]",
    "—Acabas de nacer hace dos horas.",
    "Sophie lo dijo sin énfasis. No era una pregunta ni un reproche. Era lo único que sabía con certeza en ese momento.",
    "—Lo sé. Pero tú estás aquí.",
    "Sophie lo miró durante un momento largo. Luego lo apretó un poco más contra su pecho.",
    "La Dra. Park recogió sus anotaciones. Cuatro páginas de información que no sabía cómo clasificar, sobre santuarios temporales y devoradores y 2,847 personas que todavía no sabían que tenían que elegir.",
    "El Dr. Kim revisó los equipos de la habitación. Todos funcionaban. Todos mostraban lecturas normales, como si los últimas horas no hubieran ocurrido.",
    "Salieron del hospital a las 05:44 de la madrugada. El cielo sobre Seúl comenzaba a clarear. Sophie cargaba a su hijo en brazos. El bebé tenía los ojos cerrados por primera vez desde que nació.",
    "El Dr. Kim caminó detrás de ellas y no dijo nada durante el trayecto al estacionamiento.",
    "[HTML]<div class=\"intercapitulo\"><h4>REGISTRO MÉDICO CONFIDENCIAL</h4><h5>HOSPITAL CENTRAL DE SEÚL - DEPARTAMENTO DE MATERNIDAD</h5><div class=\"document-content\"><p><strong>PACIENTE:</strong> Yun, Sophie (Caso Especial #001)</p><p><strong>FECHA DE PARTO:</strong> [CLASIFICADO]</p><p><strong>MÉDICO PRINCIPAL:</strong> Dr. Kim Jae-sung</p><p><strong>ANOMALÍAS DOCUMENTADAS:</strong></p><ul><li>Trabajo de parto de 42 horas sin signos de distrés fetal</li><li>Geometrías no-euclidianas observadas durante proceso de nacimiento</li><li>Recién nacido demostró capacidades lingüísticas inmediatas</li><li>Paciente verbalizó información de origen desconocido durante el post-parto inmediato. Cuatro páginas de anotaciones trasladadas a custodia de inteligencia militar</li><li>Personal médico experimentó alteraciones cognitivas durante el procedimiento</li><li>Instrumentos médicos registraron patrones fuera de rango documentado</li></ul><p><strong>RECOMENDACIÓN:</strong> Este caso trasciende categorías médicas tradicionales. Requiere nueva clasificación. No tengo una propuesta para esa clasificación.</p><p><strong>NOTA PERSONAL DEL DR. KIM:</strong> <em>En veinte años de medicina, pensé que había visto todo. Esta noche aprendí que no había visto nada. No sé qué es ese niño. Sé que la Dra. Yun lo ama. Y sé que eso, por alguna razón que no puedo articular médicamente, me parece relevante.</em></p><p><strong>ESTADO:</strong> Archivo trasladado a custodia militar. Copias destruidas por orden del Ministerio de Defensa.</p></div></div>"
  ]
};
