const CAPITULO = {
  numero: 3,
  titulo: "El Ojo que Todo lo Ve",
  paginas: "21-28",
  subtitulo: "Primera Comunicación Transdimensional",
  nav: {
    anterior: { href: "capitulo_02.html", label: "← Capítulo 2" },
    siguiente: { href: "capitulo_04.html", label: "Capítulo 4 →" }
  },
  contenido: [
    "[P21]",
    "[HTML]<p><strong>Centro de Comando Conjunto, Seúl - 07:15 hrs - Día 6</strong></p>",
    "[OPEN]El General Thomas Kim se despertó con la alarma de emergencia que significaba que el mundo tal como lo conocían había cambiado para siempre.",
    "Treinta y dos años de servicio militar. Tres conflictos internacionales. Dos crisis de seguridad nacional.",
    "Nada había preparado a Thomas Kim para los datos que parpadeaban en las pantallas del búnker de hormigón armado cinco pisos bajo tierra. Las paredes de acero reforzado zumbaban con el ronroneo constante de los sistemas de ventilación.",
    "La estructura ósea había crecido 400 metros en seis horas. Emitía señales que desafiaban toda clasificación conocida.",
    "[HTML]<p><strong>Valle Oscuro - Centro de la Estructura - 07:30 hrs</strong></p>",
    "Mientras Thomas observaba los datos imposibles desde el búnker subterráneo, a quince kilómetros de distancia, en el corazón mismo de la anomalía...",
    "[HTML]<p class=\"character-introduction\"><strong>Maya Park ya no se sentía completamente humana.</strong></p>",
    "Parada en el centro de la estructura que había emergido durante la noche, aún recordaba por qué había venido al valle.",
    "Algo fundamental había cambiado en ella. No entendía qué ni por qué.",
    "—General, la estructura ha alcanzado 500 metros de altura y continúa creciendo,",
    "reportó la Mayor Sarah Chen desde su estación de monitoreo. Sus dedos volaron sobre el teclado mecánico. La luz azul pálida de cuatro monitores de alta resolución iluminaba su rostro tenso.",
    "—Pero estamos recibiendo transmisiones desde el interior. En coreano perfecto.",
    "[HTML]<p><strong>Interior de la Estructura - 07:45 hrs</strong></p>",
    "—General Kim, mi nombre es Maya Park. Sé que me están escuchando.",
    "La voz era claramente de Maya. Pero había algo diferente en el tono. Su respiración era irregular, entrecortada.",
    "—Estoy... bien. Pero algo ha cambiado. Puedo escuchar voces que no son mías.",
    "[LOC]Centro de Comando - 07:46 hrs",
    "De vuelta en el búnker, la transmisión de Maya resonaba a través de los altavoces del comando. El sonido de su voz transformada llenó el aire procesado de la instalación subterránea.",
    "Thomas miró a Sarah Chen. Treinta años de experiencia militar no habían incluido protocolos para esto. Sus manos sudaban dentro de los guantes.",
    "—Maya... ¿qué ha pasado contigo? ¿Estás herida?",
    "[LOC]Interior de la Estructura - 07:47 hrs",
    "En el interior de la estructura ósea, Maya escuchó la pregunta de Thomas como si llegara desde muy lejos. Las voces en su mente susurraban explicaciones que apenas podía comprender.",
    "—No estoy herida, General Kim. Pero... no estoy sola. Hay voces aquí que hablan de cosas que pasaron hace mucho tiempo. Hablan de... despertar. De algo que estuvo esperando.",
    "Su voz tembló. Las palabras salían como si las estuviera traduciendo en tiempo real.",
    "—No entiendo todo lo que me dicen, pero... dicen que otros como yo van a empezar a escuchar las voces también. Que hay personas especiales que pueden... cambiar.",
    "[P22]",
    "—Maya, ¿puedes salir de ahí? ¿Estás atrapada?",
    "—Podría salir, pero... no sé si debería. Las voces dicen que soy un puente. Que necesito ayudar a otros a entender cuando llegue el momento.",
    "Thomas observó las pantallas. Los datos llegaban desde múltiples fuentes.",
    "Los sismógrafos registraban vibraciones anómalas. No coincidían con ningún patrón sísmico conocido.",
    "Los campos electromagnéticos fluctuaban violentamente. Los equipos más sensibles enloquecían.",
    "—Señor,",
    "interrumpió Chen. Su rostro estaba pálido bajo la luz LED azul de los monitores curvos de 34 pulgadas. El aire procesado del búnker llevaba el olor metálico de equipos electrónicos funcionando al límite.",
    "—Tenemos movimiento en el valle.",
    "La imagen satelital cambió abruptamente. Se enfocó en el borde norte de la estructura ósea.",
    "Thomas sintió que su sangre se helaba. Su respiración se volvió superficial. Los protocolos de emergencia no cubrían criaturas esqueléticas de tres metros.",
    "[P23]",
    "Una figura caminaba entre los pinos coreanos supervivientes. Sus ramas desnudas se extendían como garras contra el cielo gris del amanecer. Se movía con gracia antinatural.",
    "Medía al menos tres metros de altura. Su cuerpo era una combinación imposible de huesos humanos magnificados y estructuras que no pertenecían a ninguna anatomía terrestre.",
    "Sus brazos eran desproporcionadamente largos. Las manos terminaban en dedos de marfil que parecían capaces de atravesar acero.",
    "Su cráneo era humano, pero expandido. Las cuencas oculares brillaban con luz dorada.",
    "No tenía piel. Solo huesos pulidos de color marfil que reflejaban los primeros rayos del amanecer como prismas orgánicos. La superficie ósea mostraba vetas doradas que pulsaban con luz propia.",
    "—Dios mío,",
    "murmuró el Teniente Park. Su voz tembló a través del intercomunicador. Había visto combate en tres zonas de guerra. Nada lo había preparado para esto.",
    "—¿Qué es esa cosa?",
    "[HTML]<p><strong>Interior de la Estructura - 08:35 hrs</strong></p>",
    "—General... algo está saliendo. Puedo sentirlo. Las voces dicen que es... un guardián. Que no van a lastimar a nadie a menos que...",
    "Su transmisión se cortó abruptamente.",
    "[HTML]<p><strong>Centro de Comando - 08:36 hrs</strong></p>",
    "Thomas ya estaba en movimiento. Sus manos volaron sobre los controles.",
    "Activó protocolos que había memorizado pero esperaba nunca implementar.",
    "—Chen, active el Protocolo de Respuesta a Amenaza No Identificada Nivel 7. Necesito líneas seguras con las oficinas de enlace del Pentágono, el Ministerio de Defensa japonés y el Comando Central del Pueblo Chino.",
    "[HOOK]Mientras hablaba, la criatura en la pantalla se detuvo.",
    "Lentamente, muy lentamente, levantó su cabeza hacia el cielo. Como si pudiera sentir los ojos electrónicos que la observaban desde el espacio.",
    "Entonces, de manera imposible, pareció mirar directamente a través de la cámara del satélite.",
    "[P24]",
    "[HTML]<p><strong>Valle Oscuro - Perímetro Norte - 08:40 hrs</strong></p>",
    "La criatura no atacó. Se acercó lentamente al perímetro establecido por las fuerzas militares.",
    "Simplemente se quedó allí. Como si estuviera esperando algo.",
    "Durante los siguientes veinte minutos, la observaron a través de cámaras de largo alcance.",
    "Permanecía completamente inmóvil. No mostraba signos de agresión. Tampoco de retirada.",
    "Entonces, en el minuto veintiuno, giró la cabeza.",
    "No hacia la cámara. Hacia Thomas. Hacia el hombre específico que estaba mirando la pantalla a cinco pisos bajo tierra, a quince kilómetros de distancia. Thomas se apartó del monitor antes de darse cuenta de que lo había hecho.",
    "[HTML]<p><strong>Interior de la Estructura - 09:00 hrs</strong></p>",
    "Finalmente, la transmisión de Maya se reanudó.",
    "—General, las voces dicen que... que el guardián está esperando. Que quiere que sepan que no van a hacer daño si no se sienten amenazados.",
    "—También dicen que esto es solo el comienzo. Que hay otros lugares como este despertando. Pero no me dicen dónde ni cuándo.",
    "—Maya, ¿qué quieren? ¿Qué quieren estas... voces?",
    "Hubo una larga pausa antes de que Maya respondiera.",
    "Cuando lo hizo, su voz sonaba como si estuviera luchando por encontrar las palabras correctas. Como si las estuviera traduciendo desde un idioma que no conocía.",
    "—Quieren... reunirse. Dicen que han estado separados durante mucho tiempo. Y que ahora es tiempo de... recordar.",
    "[P25]",
    "[HTML]<p><strong>Puesto Avanzado Delta - 60 km al Norte - 09:15 hrs</strong></p>",
    "Mientras la criatura guardiana observaba inmóvil el perímetro del Valle Oscuro, los efectos de su presencia se extendían como ondas invisibles a través de la región montañosa.",
    "A sesenta kilómetros al norte, el Cabo Jonathan Morales y el Soldado Miguel Santos mantenían guardia en el Puesto Avanzado Delta.",
    "Hasta esa noche había sido una asignación tranquila. Puesto de observación con vista a valles montañosos cubiertos de niebla. Los dos mexicanos habían solicitado servir juntos después de desarrollar una amistad férrea durante el entrenamiento básico en Fort Benning.",
    "—¿Sientes eso?",
    "preguntó Jonathan. Ajustó su casco con manos que empezaban a temblar. Los binoculares nocturnos mostraban el horizonte normal, pero algo en su interior gritaba peligro.",
    "Había algo en el aire. Una vibración que venía de la tierra misma. Como el latido de un corazón gigantesco.",
    "—La radio está actuando raro,",
    "reportó Miguel. Golpeó suavemente la radio militar PRC-117G. Las luces indicadoras parpadeaban erráticamente en patrones que no seguían ningún manual de operaciones.",
    "—Mucha estática, pero a veces parece que hay... voces ahí adentro.",
    "Jonathan se acercó a escuchar. Su entrenamiento le decía que investigara. Su instinto le gritaba que huyera.",
    "Entre el ruido blanco y las interferencias, había susurros. En un idioma que no reconocía, pero que le resultaba familiar.",
    "Su cuerpo reconocía esos sonidos. La piel se le erizó. Los vellos de los brazos se alzaron. Su mente se negaba a procesar por qué un idioma desconocido le resultaba familiar.",
    "—Miguel... ¿alguna vez has tenido sueños en idiomas que no conoces?",
    "—¿Por qué preguntas eso, hermano?",
    "—Porque creo que entiendo lo que están diciendo.",
    "[P26]",
    "[HTML]<p><strong>Centro de Comando - 09:30 hrs</strong></p>",
    "En el momento exacto en que Jonathan pronunciaba esas palabras perturbadoras, las pantallas del centro de comando registraban anomalías similares en múltiples ubicaciones.",
    "Thomas Kim recibió reportes similares de otros tres puestos avanzados.",
    "Interferencias de radio extrañas. Vibraciones subterráneas. Soldados reportando sueños inusuales.",
    "—Chen, ¿está viendo un patrón aquí?",
    "Thomas señaló las pantallas que mostraban las ubicaciones de los reportes. Puntos rojos formando un patrón concéntrico perfecto—como si algo irradiara desde el Valle Oscuro.",
    "—Los reportes se están extendiendo en un radio de aproximadamente 100 kilómetros desde el valle.",
    "—Sí, señor.",
    "Sarah revisó los datos. Sus dedos temblaron sobre el teclado—temblor que no podía controlar. Diez años analizando inteligencia militar. Esto desafiaba toda lógica.",
    "—Y todos los soldados que reportan las interferencias más fuertes tienen algo en común según sus expedientes médicos.",
    "—¿Qué tienen en común?",
    "—Todos tienen anomalías menores en sus análisis de sangre de rutina.",
    "Sarah hizo una pausa. Verificó los datos dos veces, luego tres. Se mordió el labio inferior—hábito nervioso de la infancia que creía superado.",
    "—Nada significativo médicamente, pero... patrones similares en su ADN. Secuencias en partes del código genético que normalmente no tienen función conocida—lo que los científicos llaman 'ADN basura'.",
    "Thomas sintió un escalofrío que atravesó el uniforme militar. Sus manos buscaron automáticamente el arma reglamentaria—gesto inútil contra lo que fuera que estuvieran enfrentando.",
    "[HTML]<p><strong>Interior de la Estructura - 09:45 hrs</strong></p>",
    "Mientras Thomas asimilaba las implicaciones de los patrones genéticos, en el corazón de la estructura ósea, Maya sintió que las voces se organizaban en su mente con mayor claridad.",
    "La voz de Maya llegó una vez más.",
    "Esta vez sonaba diferente. Más clara. Más segura.",
    "—General Kim, las voces dicen que ya es suficiente por ahora. Que necesitan tiempo para... preparar las próximas fases.",
    "—Dicen que no intenten entrar en la estructura todavía. Que cuando estén listos para el próximo paso, lo sabrán.",
    "—Maya, ¿volveremos a tener noticias tuyas?",
    "—Sí, General. Cuando llegue el momento de que otros entiendan lo que yo estoy empezando a entender.",
    "Y con eso, las transmisiones cesaron.",
    "[P27]",
    "[HTML]<p><strong>Centro de Comando - 10:00 hrs</strong></p>",
    "Thomas Kim se quedó mirando las pantallas.",
    "Una estructura ósea masiva en silencio. Una criatura guardiana que permanecía inmóvil en el perímetro.",
    "—Chen, prepare un informe para el alto mando. Pero manténgalo en términos de 'anomalía geológica' y 'posible bioterrorismo' por ahora.",
    "—¿No van a mencionar las transmisiones de Maya o las criaturas esqueléticas?",
    "—No hasta que entendamos mejor qué está pasando. Si Maya tiene razón y hay otros lugares como este 'despertando', necesitamos estar preparados. Pero el pánico masivo no nos va a ayudar.",
    "Thomas miró una vez más hacia las pantallas.",
    "La criatura guardiana seguía inmóvil bajo la luz del amanecer. Sus huesos reflejaban los primeros rayos del sol como prismas de marfil. Las montañas circundantes se alzaban cubiertas de pine trees y rocas de granito.",
    "—Algo me dice que este es solo el comienzo de algo mucho más grande de lo que podemos imaginar.",
    "[P28]",
    "[HTML]<p><strong>Valle Oscuro - Interior de la Estructura - 10:15 hrs</strong></p>",
    "Maya Park se quedó sola en el corazón de la estructura ósea. Debería sentir terror. Debería estar gritando. En lugar de eso, una calma antinatural la llenaba—lo cual era más aterrador que el miedo.",
    "Intentó recordar la cara de Jung-ho. La recordó. Pero donde antes esa imagen traía consigo un peso específico en el pecho—ese nudo que había cargado cada día desde que él murió—ahora solo había reconocimiento. Sabía que su hermano importaba. No podía sentir por qué. Bajó la vista a sus manos y las encontró completamente quietas.",
    "Escuchaba voces que susurraban secretos de épocas anteriores a la humanidad. Secretos de cuando la Tierra era joven y las estrellas tenían otros nombres—hace 230 millones de años, mucho antes que los dinosaurios, antes que cualquier forma de vida compleja que conocieran.",
    "No entendía todo lo que le decían.",
    "Pero una cosa quedaba clara: esto era solo el primer paso. Algo que había estado planeándose durante mucho tiempo.",
    "En algún lugar profundo de su mente transformada, Maya comprendió algo fundamental.",
    "Su trabajo como investigadora había terminado. Ahora era algo nuevo: un traductor entre mundos que apenas estaban comenzando a conocerse, actuando de puente entre dos formas de existencia.",
    "[HOOK]Las voces le susurraron algo más.",
    "Pronto, muy pronto, otros como ella comenzarían a despertar. Personas que llevaban en su ADN fragmentos de algo anterior a la humanidad—latente, esperando la señal correcta para activarse.",
    "Cuando eso pasara, el verdadero trabajo podría comenzar."
  ]
};
