const CAPITULO = {
  numero: 6,
  titulo: "Los Danzarines de Cristal",
  paginas: "45-52",
  nav: {
    anterior: { href: "capitulo_05.html", label: "← Capítulo 5" },
    siguiente: { href: "capitulo_07.html", label: "Capítulo 7 →" }
  },
  contenido: [
    "[P45]",
    "[OPEN]Miguel Santos disparó su rifle automático durante tres segundos completos antes de darse cuenta de que las balas atravesaban a las criaturas sin causarles daño alguno.",
    "Miguel había observado los cambios en Jonathan con terror creciente. Su hermano de armas extendía la mano hacia entidades que no deberían existir.",
    "Los ojos de Jonathan habían cambiado. Su voz resonaba con armónicos imposibles: frecuencias múltiples dentro de una sola garganta.",
    "Cada fibra del entrenamiento militar de Miguel gritaba una respuesta: neutralizar la amenaza. Pero algo más profundo en él luchaba contra ese instinto.",
    "Las balas atravesaban a las criaturas sin efecto.",
    "Jonathan lo miraba con una expresión de profunda tristeza. Era peor que cualquier herida física.",
    "[HTML]<p><span class=\"dialogue\">—Miguel, hermano,</span> Jonathan habló, y a pesar de los cambios, Miguel podía escuchar al hombre que conocía debajo de esas nuevas capas de resonancia.</p>",
    "—Sé que esto es terrorífico. Sé que no tiene sentido. Pero necesitas entender - ellos no son enemigos. Nunca lo fueron.",
    "[HTML]<p><span class=\"dialogue\">—¡Tú no eres Jonathan!</span> Miguel gritó, pero su voz se quebró.</p>",
    "No era ira lo que dominaba sus emociones, sino miedo. Miedo de perder al único hermano que le quedaba en el mundo.",
    "—¡Mi amigo no hablaría así! ¡Mi amigo no... no brillaría así!",
    "[HOOK]La criatura de marfil que había iniciado todo levantó una mano, y el rifle de Miguel simplemente se desintegró. No se derritió, no se rompió: cada átomo que lo componía se separó pacíficamente, convirtiéndose en polvo dorado que flotó suavemente hasta el suelo.",
    "[P46]",
    "[HTML]<p class=\"skeleton-sighting danzarines-cristal\">Fue entonces cuando Miguel vio a los otros. Habían estado ahí todo el tiempo, pero de alguna manera su mente había sido incapaz de procesarlos completamente hasta este momento. Criaturas que parecían estar hechas enteramente de cristales de hueso que tintineaban musicalmente con cada movimiento. Su forma era vagamente humana, pero estilizada, como si hubieran sido esculpidas por un artista que entendía la belleza más allá de las limitaciones biológicas.</p>",
    "[HTML]<p class=\"skeleton-description danzarines-cristal\">Se movían en patrones que recordaban a una danza antigua, sus cuerpos cristalinos refractando la luz de la luna en prismas que llenaban el aire nocturno de arcoíris espectrales. Con cada paso, con cada gesto, producían música: no solo el tintineo de cristal contra cristal, sino armonías complejas que resonaban en algo más profundo que el sonido, algo en el ADN de Miguel.</p>",
    "[HTML]<p><span class=\"dialogue latin-inscription\">—Los Danzarines de Cristal,</span> murmuró Jonathan, y Miguel se dio cuenta de que él también conocía ese nombre, como si siempre hubiera estado en su memoria esperando ser recordado. <span class=\"dialogue\">—Fueron músicos antes de convertirse en guardianes. Su música podía crear realidades, doblar el espacio-tiempo, hacer que las estrellas danzaran en nuevos patrones.</span></p>",
    "[HTML]<p><span class=\"dialogue\">—¿Cómo puedes saber eso?</span> Miguel preguntó, pero incluso mientras hablaba, imágenes comenzaron a filtrarse en su propia mente: conciertos que duraban siglos, orquestas de miles de seres cristalinos creando sinfonías que podían dar nacimiento a nuevos universos.</p>",
    "[HTML]<p><span class=\"dialogue\">—Porque tú también fuiste uno de ellos, Miguel.</span> La voz vino de la criatura de marfil, pero ahora sonaba menos aliena, más familiar. <span class=\"dialogue\">—Fuiste el maestro compositor, el que creó la Sinfonía de la Fragmentación que nos permitió dispersarnos sin perder nuestra esencia.</span></p>",
    "[P47]",
    "En el Centro de Comando, los sistemas de comunicación habían comenzado a captar algo imposible: música que llegaba desde múltiples puntos alrededor del perímetro del valle, pero que se coordinaba perfectamente como si fuera interpretada por una sola orquesta masiva.",
    "[HTML]<p><span class=\"dialogue\">—General, está recibiendo esto?</span> Sarah Chen ajustó sus auriculares, su rostro pálido bajo la luz de las pantallas. <span class=\"dialogue\">—Son nuestros puestos avanzados. Todos están transmitiendo la misma... composición.</span></p>",
    "Thomas tomó los auriculares y escuchó. No era música en el sentido convencional. Era algo más profundo, más fundamental: como si estuviera oyendo la canción que las partículas subatómicas cantaban mientras formaban la materia, la melodía que seguían los planetas mientras orbitaban alrededor de sus estrellas.",
    "—¿Cuántos puestos están involucrados?",
    "—Todos, señor. Doce instalaciones en un radio de cien kilómetros. Y no solo están transmitiendo la música... nuestros soldados la están interpretando —cantando en idiomas que nunca aprendieron, con voces que no son completamente suyas—.",
    "Chen se detuvo. Tenía una foto laminada pegada en el lateral de su tableta, pequeña, desgastada en las esquinas. La cubrió con el pulgar antes de continuar.",
    "—Entre los que cantan... está el Teniente Rao. Es mi cuñado, señor.",
    "Nadie respondió. Thomas no devolvió los auriculares.",
    "Sophie había estado observando los monitores médicos que seguían su condición y la de su bebé. Se acercó a las pantallas de comunicación.",
    "—General, necesito escuchar eso.",
    "Cuando se puso los auriculares, su bebé inmediatamente comenzó a moverse.",
    "Pero no con agitación. Con ritmo. Como si estuviera danzando al compás de la música imposible.",
    "[HTML]<p><span class=\"dialogue hook\">—Dios mío,</span> susurró. <span class=\"dialogue\">—Mi bebé... mi bebé conoce esta canción.</span></p>",
    "[P48]",
    "Trevor Williams había visto muchas cosas en su carrera con la DEA que habían desafiado su comprensión del mundo. Carteles que operaban con eficiencia militar, drogas que creaban adicciones psicológicas en minutos, organizaciones criminales que parecían tener recursos ilimitados. Pero nunca había visto soldados entrenados abandonar sus posiciones para formar círculos y comenzar a entonar canciones en idiomas que no deberían conocer.",
    "[HTML]<p><span class=\"dialogue\">—Esto no es solo una reacción al polvo de hueso,</span> murmuró, estudiando los reportes que llegaban desde el perímetro. <span class=\"dialogue\">—Esto es coordinado. Como si todas estas personas estuvieran siguiendo un guión que nunca leyeron pero que conocen de memoria.</span></p>",
    "[HTML]<p><span class=\"dialogue\">—¿Qué está sugiriendo?</span> preguntó Thomas.</p>",
    "—Que no estamos lidiando con una invasión en el sentido tradicional. Estamos presenciando una reunión. Como si estas criaturas no vinieran de afuera, sino que hubieran estado aquí todo el tiempo, durmiendo, esperando a que algo las despertara.",
    "[HTML]<p>Sophie se quitó los auriculares bruscamente, su rostro ahora bañado en sudor. <span class=\"dialogue\">—No están esperando a que algo las despierte. Están esperando a que nosotros despertemos.</span></p>",
    "—¿Qué quiere decir?",
    "[HTML]<p class=\"dialogue major-revelation\">—La música, los patrones, todo esto... no es para controlar a nuestros soldados. Es para recordarles quiénes eran antes de ser humanos. Cada uno de esos soldados allá afuera lleva fragmentos de consciencias cósmicas que existieron durante millones de años antes de que la humanidad evolucionara.</p>",
    "[P49]",
    "En el Puesto Avanzado Delta, Miguel bajó las manos. Las memorias seguían llegando y él dejó de empujarlas hacia atrás. Se quedó inmóvil, los hombros sueltos, los ojos abiertos hacia algo que no era el bosque. Se vio dirigiendo orquestas de millones de seres cristalinos, componiendo sinfonías que podían remodelar galaxias, creando música tan hermosa que civilizaciones enteras habían llorado durante siglos solo por el privilegio de escucharla una vez.",
    "Y recordó el momento de la decisión. La gran fragmentación —el momento cuando las civilizaciones ancestrales eligieron sacrificarse—. El amor tan puro que había motivado a Eloria y a los veinticuatro reinos a destruirse a sí mismos para dar a unas criaturas primitivas la oportunidad de elegir su propio destino.",
    "[HTML]<p><span class=\"dialogue\">—Nosotros elegimos esto,</span> murmuró, mirando sus propias manos como si las viera por primera vez. <span class=\"dialogue\">—Elegimos olvidar, elegimos dispersarnos, elegimos vivir como humanos hasta que llegara el momento de recordar.</span></p>",
    "[HTML]<p>El Danzarín de Cristal más cercano se acercó, extendiendo una mano que refractaba la luz en miles de colores. <span class=\"dialogue\">—Y ahora ha llegado ese momento, Maestro Miguel. Los devoradores se acercan. En menos de tres años terrestres, llegarán a este sistema solar con el mismo hambre que han llevado a un millón de mundos antes que este.</span></p>",
    "—¿Y qué podemos hacer nosotros? Somos solo fragmentos, sombras de lo que fuimos una vez.",
    "[HTML]<p class=\"dialogue hook\">—Podéis elegir recordar completamente. Podéis elegir reuniros, reconstruir lo que fuisteis, convertiros otra vez en los guardianes que este mundo necesita.</p>",
    "—¿Y si elegimos seguir siendo humanos?",
    "El silencio que siguió a esa pregunta fue más elocuente que cualquier respuesta.",
    "[P50]",
    "Sophie había comenzado a experimentar contracciones. Pero no las contracciones del parto prematuro que los médicos habrían reconocido.",
    "Estas eran rítmicas, musicales, sincronizadas con la canción imposible que seguía llegando desde el perímetro.",
    "Su bebé no estaba tratando de nacer prematuramente; estaba tratando de comunicarse.",
    "[HTML]<p><span class=\"dialogue\">—General, necesito ir al valle,</span> dijo, su voz tensa por algo que no era dolor físico. <span class=\"dialogue\">—Mi bebé... mi bebé está tratando de decirme algo, pero no puedo entenderlo desde aquí.</span></p>",
    "—Doctora, eso es imposible. Es demasiado peligroso.",
    "[HTML]<p><span class=\"dialogue\">—No para mí. No para nosotros.</span> Se tocó el vientre, donde su hijo se movía en patrones cada vez más complejos.</p>",
    "—No somos solo humanos, ¿verdad? Somos algo más. Somos lo que ellos estuvieron esperando.",
    "Trevor se acercó a ella. Estudió sus ojos donde las motas doradas ahora pulsaban claramente.",
    "—Doctora, ¿qué es lo que realmente piensa que está pasando aquí?",
    "[HTML]<p class=\"dialogue major-revelation\">—Creo que estamos presenciando el final de la infancia de la humanidad. Durante 230 millones de años, hemos sido niños jugando con juguetes, sin saber que llevamos dentro los fragmentos de dioses que se sacrificaron por nosotros. Pero los devoradores que obligaron a ese sacrificio original se acercan otra vez.</p>",
    "—¿Y?",
    "—Y ahora tenemos que elegir si queremos crecer y convertirnos en lo que siempre tuvimos el potencial de ser, o si preferimos morir como la especie limitada que pensábamos que éramos.",
    "[P51]",
    "Los Danzarines de Cristal habían comenzado una nueva composición, una que resonaba no solo en el aire sino directamente en la estructura molecular de todo lo que los rodeaba. Miguel vio cómo los árboles comenzaron a cristalizarse lentamente, no muriendo sino transformándose en algo que era simultáneamente vegetal y mineral, orgánico y eterno.",
    "[HTML]<p><span class=\"transformation-sequence\">—Están preparando el terreno,</span> realizó Jonathan. Sus nuevas memorias le proporcionaban contexto para lo imposible.</p>",
    "—Cuando los 2,847 estemos reunidos, cuando hayamos elegido recordar, necesitaremos un espacio que pueda contener lo que nos convertiremos.",
    "[HTML]<p><span class=\"dialogue\">—¿Y qué nos convertiremos?</span> preguntó Miguel, aunque parte de él ya conocía la respuesta.</p>",
    "—En los únicos seres en este universo capaces de enfrentar a los devoradores. En los guardianes que este mundo ha estado esperando durante 230 millones de años.",
    "Miguel miró sus propias manos. Notó por primera vez las líneas doradas que habían comenzado a aparecer bajo su piel.",
    "Seguían patrones que recordaban circuitos eléctricos —pero infinitamente más complejos.",
    "—¿Y si no queremos? ¿Y si preferimos seguir siendo humanos?",
    "Jonathan lo miró con ojos que ahora brillaban constantemente con esa luz interna.",
    "—Entonces moriremos como humanos. Junto con todo lo demás en este planeta.",
    "[HOOK]En la distancia, más música comenzó a sonar. Pero esta no venía de los Danzarines de Cristal. Venía de la estructura ósea en el valle, que ahora se alzaba hacia el cielo en torres sin ángulos rectos, sin proporción humana, sin memoria de la gravedad. Y llevaba una melodía que depositó en ambos soldados algo antiguo, seguro: una quietud que no pedían permiso para entrar.",
    "[P52]",
    "En el Centro de Comando, todas las comunicaciones se cortaron simultáneamente. Las pantallas mostraron estática durante aproximadamente treinta segundos, y luego se aclararon para mostrar una imagen que dejó a todos los presentes sin aliento.",
    "El valle ya no era un valle. Se había convertido en una ciudad.",
    "[HTML]<p class=\"city-description\">No una ciudad construida con herramientas y materiales, sino crecida orgánicamente. Torres que se alzaban como huesos gigantescos, conectadas por arcos que desafiaban la física, plazas circulares donde la luz dorada pulsaba como corazones latientes. Y por todas partes, figuras. Humanos que caminaban junto a criaturas esqueléticas, no como prisioneros o víctimas, sino como compañeros, como familia que se reencuentra después de una separación de eones.</p>",
    "[HTML]<p><span class=\"dialogue\">—¿Cuántas personas hay ahí?</span> murmuró Thomas.</p>",
    "[HTML]<p><span class=\"dialogue\">—Contando... aproximadamente mil doscientas,</span> respondió Chen, estudiando los datos de reconocimiento. <span class=\"dialogue\">—Todas en nuestra lista de los 2,847.</span></p>",
    "—Menos de la mitad.",
    "—Sí, señor. Los otros... todavía están eligiendo.",
    "Sophie se acercó a la ventana blindada del centro de comando. Miró hacia el horizonte donde el resplandor dorado había transformado la noche en algo que se parecía más al amanecer de un mundo diferente.",
    "[HTML]<p><span class=\"dialogue cliffhanger\">—No,</span> dijo suavemente.</p>",
    "—Los otros todavía están recordando. Y cuando todos recordemos, cuando los 2,847 estemos completos... entonces los verdaderos devoradores sabrán que hemos despertado. Y vendrán.",
    "[HTML]<div class=\"intercapitulo\"><h4>INTERCAPÍTULO 6</h4><h5>DIARIO PERSONAL - MIGUEL SANTOS</h5><div class=\"document-header\"><p><strong>FECHA:</strong> [Última entrada antes de los eventos]</p><p><strong>UBICACIÓN:</strong> Base Militar, Corea del Sur</p><p><strong>NOTA:</strong> Encontrado en sus pertenencias personales</p></div><div class=\"document-content\"><p><em>Mamá siempre decía que los Santos teníamos música en la sangre. Que el bisabuelo Carlos podía hacer llorar a la gente solo con su guitarra, que había algo especial en la forma en que nuestra familia entendía la música —una conexión que iba más allá del talento normal—.</em></p><p><em>Nunca entendí lo que quería decir hasta ahora.</em></p><p><em>Anoche soñé que dirigía una orquesta de millones de músicos, y que la música que hacíamos podía cambiar la forma de las estrellas. Sonaba loco cuando me desperté, pero ahora... ahora estoy escuchando esa misma música en el viento.</em></p><p><em>Jonathan dice que él también tiene sueños extraños. Que se ve a sí mismo como algún tipo de general en guerras que se libraron antes de que existieran los humanos. Nos reímos de ello durante el desayuno, pero después, cuando practicábamos tácticas militares, ambos sabíamos movimientos que nunca habíamos aprendido.</em></p><p><em>Algo está despertando. En nosotros, en el mundo, en algo mucho más grande que no entiendo todavía.</em></p><p><em>¿Es esto lo que sentiste, bisabuelo? ¿Era esto lo que escribiste en ese diario que mamá nunca me dejó leer completamente?</em></p><p><em>Si alguien encuentra esto después de que algo me pase, díganle a mi familia que no tuve miedo. Que lo que sea que esté pasando, se siente como volver a casa.</em></p></div></div>",
  ]
};
