const CAPITULO = {
  numero: 8,
  titulo: "Primera Sangre",
  paginas: "61-68",
  nav: {
    anterior: { href: "capitulo_07.html", label: "← Capítulo 7" },
    siguiente: { href: "capitulo_08_5.html", label: "Capítulo 8.5 →" }
  },
  contenido: [
    "[P61]",
    "[LOC]Centro de Comando Conjunto - 14:30 hrs - Día 8",
    "[OPEN]La Mayor Sarah Chen sabía que esta sería una misión de la que podría no regresar, pero alguien tenía que obtener inteligencia real sobre las entidades.",
    "Ocho días habían pasado desde el primer contacto con Maya transformada. Ocho días de observar estructuras óseas emerger en múltiples ubicaciones.",
    "Las fuerzas militares necesitaban información táctica real sobre capacidades e intenciones de las entidades.",
    "[HTML]<p class=\"dialogue thomas-mission-briefing\">—Chen, la misión de reconocimiento es voluntaria pero crítica,</p>",
    "declaró el General Kim.",
    "—Necesitamos saber si estas criaturas pueden ser detenidas por medios convencionales. Su experiencia en inteligencia arqueológica la convierte en la persona más calificada para interpretar lo que encuentre.",
    "[HTML]<p class=\"dialogue sarah-acceptance\">—Entiendo los riesgos, General. Pero si no entendemos qué enfrentamos, no podemos proteger a nadie.</p>",
    "[HTML]<div class=\"parallel-scene-break\"><p class=\"location-marker\"><em>Valle Oscuro - Perímetro Exterior - 15:00 hrs</em></p></div>",
    "Sarah lideró un equipo de reconocimiento de cinco especialistas hacia la estructura ósea más pequeña que había emergido al este del valle principal.",
    "A diferencia de la Catedral central donde estaba Maya, esta estructura parecía estar menos activa. La convertía en un objetivo más seguro para obtener inteligencia.",
    "[HTML]<p class=\"dialogue sarah-team-briefing\">—Recordemos el protocolo: observación pasiva únicamente. No hacemos contacto directo con ninguna entidad. Documentamos capacidades, patrones de movimiento, y cualquier vulnerabilidad aparente.</p>",
    "[HTML]<p class=\"dialogue specialist-torres\">—Mayor, ¿qué hacemos si nos detectan?</p>",
    "[HTML]<p class=\"dialogue sarah-protocol\">—Retirada inmediata. Esta es misión de inteligencia, no de combate.</p>",
    "[P62]",
    "Lo que encontraron desafió todas sus expectativas tácticas.",
    "Las criaturas esqueléticas no patrullaban el área como guardianes defensivos. Trabajaban. Construían.",
    "Tres entidades de aproximadamente cuatro metros de altura movían bloques de material óseo con precisión quirúrgica. Expandían la estructura según patrones geométricamente perfectos.",
    "[HTML]<p class=\"dialogue sarah-field-observation\">—Control, esto es Reconocimiento Alpha. Las entidades no muestran comportamiento agresivo. Parecen estar... construyendo algo.</p>",
    "[HTML]<p class=\"dialogue thomas-radio\">—¿Construyendo qué, Chen?</p>",
    "[HTML]<p class=\"dialogue sarah-analyzing\">—No lo sé, señor. Pero los patrones sugieren algún tipo de... estación de recepción. Como si estuvieran preparando la estructura para recibir algo más grande.</p>",
    "Durante dos horas, el equipo observó y documentó. Las criaturas parecían completamente inconscientes de su presencia, concentradas totalmente en su trabajo de construcción.",
    "Sarah comenzó a relajarse. Pensó que podrían completar la misión sin incidentes.",
    "Esa fue su primera equivocación táctica.",
    "[HTML]<div class=\"parallel-scene-break\"><p class=\"location-marker\"><em>Centro de Comando - 17:15 hrs</em></p></div>",
    "[HTML]<p class=\"dialogue sarah-status-report\">—Control, hemos documentado suficiente para el análisis inicial. Iniciando retirada según protocolo.</p>",
    "[HTML]<p class=\"dialogue thomas-confirmation\">—Recibido, Alpha. Buen trabajo, Chen.</p>",
    "Pero mientras el equipo se retiraba, algo cambió.",
    "Las tres criaturas constructoras se detuvieron simultáneamente. Levantaron sus cabezas elongadas.",
    "Por primera vez en dos horas, miraron directamente hacia la posición del equipo de reconocimiento.",
    "[P63]",
    "[HTML]<p class=\"dialogue sarah-tactical-alert\">—Control, hemos sido detectados. Las entidades han interrumpido su trabajo y están... observándonos.</p>",
    "[HTML]<p class=\"dialogue thomas-immediate-response\">—Chen, retire su equipo inmediatamente. No esperen a ver qué pasa.</p>",
    "Pero antes de que pudieran moverse, las criaturas hicieron algo completamente inesperado.",
    "En lugar de acercarse agresivamente, una de ellas levantó lo que parecía ser una mano en un gesto que solo podía describirse como un saludo.",
    "[HTML]<p class=\"dialogue specialist-martinez\">—Mayor... ¿esa cosa nos está saludando?</p>",
    "[HTML]<p class=\"dialogue sarah-confused\">—Parece que sí. Control, las entidades no muestran intenciones hostiles. Una de ellas parece estar tratando de... comunicarse.</p>",
    "Esa fue su segunda equivocación táctica.",
    "La criatura que había saludado comenzó a caminar lentamente hacia ellos.",
    "No de manera amenazante, sino con cautela, sin movimientos bruscos. Sus movimientos eran deliberadamente no amenazantes. Sus brazos visibles, su postura relajada.",
    "[HTML]<p class=\"dialogue sarah-field-decision\">—Control, solicito permiso para establecer contacto limitado. La entidad parece no hostil y esto podría ser nuestra oportunidad de obtener información directa.</p>",
    "[HTML]<p class=\"dialogue thomas-denied\">—Negativo, Chen. Retire su equipo ahora.</p>",
    "[HTML]<p class=\"dialogue sarah-pressing\">—Señor, con respeto, esta podría ser nuestra única oportunidad de entender sus intenciones antes de...</p>",
    "Su tercera y fatal equivocación táctica fue no notar que las otras dos criaturas habían desaparecido durante la conversación.",
    "[P64]",
    "[HTML]<p class=\"skeleton-emergence\">Las dos criaturas emergieron desde ángulos que deberían haber sido imposibles. No de la tierra o de detrás de las rocas, sino literalmente materializándose desde espacios que parecían estar vacíos momentos antes.</p>",
    "Sus movimientos no eran agresivos. Eran tácticos. Profesionales.",
    "Como si hubieran estudiado las mismas manuales militares que el equipo de Sarah.",
    "[HTML]<p class=\"dialogue sarah-tactical-recognition\">—¡Es una maniobra de flanqueo! ¡Dispersión inmediata!</p>",
    "Pero el equipo de Sarah había sido entrenado para combate humano contra humano. Estas entidades se movían según reglas diferentes.",
    "Una de ellas alcanzó al Especialista Torres antes de que pudiera dar tres pasos. Pero en lugar de atacarlo, simplemente lo tocó.",
    "Torres se detuvo inmediatamente. No porque estuviera herido, sino porque su expresión había cambiado completamente.",
    "Sus ojos mostraban reconocimiento. Como si acabara de recordar algo que había olvidado durante mucho tiempo.",
    "[HTML]<p class=\"dialogue torres-transformed\">—Sarah... no son enemigos. Solo... solo quieren que recordemos.</p>",
    "[HTML]<p class=\"dialogue sarah-desperate\">—¡Torres, mantén la posición! ¡No sabemos qué te hicieron!</p>",
    "Torres ya no estaba siguiendo órdenes militares. Se acercó lentamente a Sarah.",
    "Ella pudo ver que algo fundamental había cambiado en él. No parecía amenazante, pero tampoco parecía completamente humano.",
    "[HTML]<p class=\"dialogue torres-pleading\">—Sarah, puedo ver lo que somos realmente. Lo que siempre fuimos. Solo necesitas dejar que te muestren...</p>",
    "[P65]",
    "[HTML]<p class=\"dialogue sarah-command-decision\">—¡Todos retrocedan! ¡Torres ha sido comprometido!</p>",
    "Sarah tomó la decisión táctica que había sido entrenada para tomar: neutralizar la amenaza inmediata.",
    "Abrió fuego no sobre las criaturas, sino sobre Torres. Tres disparos al centro de masa, protocolo estándar.",
    "Torres colapsó, pero las balas no lo habían matado. Donde la munición había impactado, su cuerpo se estaba reparando.",
    "Los agujeros se cerraban con material que parecía hueso líquido. Sus ojos, ahora dorados, la miraron con una expresión de profunda tristeza.",
    "[HTML]<p class=\"dialogue torres-dying-words\">—Sarah... no tenías que tener miedo. Solo querían ayudarnos a ser mejores...</p>",
    "Esas fueron las últimas palabras de Torres como algo reconocible como humano.",
    "Su cuerpo comenzó a cambiar rápidamente. Se alargaba, los huesos se reestructuraban según patrones que no pertenecían a ninguna anatomía terrestre.",
    "[HTML]<p class=\"dialogue sarah-horrified\">—Control, Torres ha sido completamente transformado. Repito, hemos perdido a Torres por transformación hostil.</p>",
    "Las criaturas originales se acercaron más. Sarah pudo ver que sus expresiones habían cambiado.",
    "Ya no parecían curiosas o amigables. Parecían decepcionadas.",
    "[HTML]<p class=\"dialogue creature-communication\">Una de ellas habló. Aunque usaba una voz que había pertenecido a alguien humano, las palabras llegaron directamente a la mente de Sarah:</p>",
    "—Hermana guerrera, has elegido el miedo sobre la comprensión. Esa elección tiene consecuencias.",
    "[P66]",
    "Sarah había estado en combate antes. Había enfrentado terroristas en tres continentes, había sobrevivido a situaciones que habían quebrado soldados más experimentados.",
    "Pero esto era diferente. Estas criaturas no querían matarla; querían cambiarla.",
    "Y de alguna manera, eso era infinitamente más aterrador.",
    "[HTML]<p class=\"dialogue sarah-last-transmission\">—Control, estoy iniciando protocolo de extracción de emergencia. Mi equipo ha sido comprometido. Repito, iniciando...</p>",
    "Nunca completó esa transmisión.",
    "La criatura que había hablado se movió con velocidad que desafió la percepción humana.",
    "Un momento estaba a diez metros de distancia, el siguiente estaba directamente frente a Sarah.",
    "Pero en lugar de tocarla como había hecho con Torres, hizo algo diferente.",
    "[HTML]<p class=\"sarah-death-sequence\">Extendió su mano hacia ella, pero no para transformarla. Para mostrarle algo.</p>",
    "En el aire entre ellos, imágenes comenzaron a formarse. Visiones de lo que la Tierra se convertiría si la transformación continuaba.",
    "Ciudades de hueso y carne viviente donde el dolor había sido eliminado, donde la muerte era opcional, donde la humanidad había evolucionado más allá de sus limitaciones actuales.",
    "Pero también le mostró el costo: todo lo que ella reconocía como humanidad desaparecería.",
    "El sufrimiento terminaría, pero también la lucha. El crecimiento. La elección.",
    "—No,",
    "susurró Sarah, comprendiendo finalmente la verdadera elección que enfrentaba la humanidad.",
    "—No van a robarnos el derecho a seguir siendo humanos, sin importar qué tan imperfectos seamos.",
    "[P67]",
    "Sarah Chen tomó su última decisión táctica como oficial de inteligencia militar de la Tierra: activó la granada de fragmentación que llevaba en su chaleco, manteniéndola firmemente contra su pecho.",
    "[HTML]<p class=\"dialogue sarah-final-words\">—Control... digan al General Kim... que algunas líneas no deben cruzarse. Sin importar las promesas que nos hagan.</p>",
    "La explosión fue lo suficientemente poderosa como para ser detectada por los sismógrafos a cincuenta kilómetros de distancia.",
    "[HTML]<div class=\"parallel-scene-break\"><p class=\"location-marker\"><em>Centro de Comando - 17:45 hrs</em></p></div>",
    "[HTML]<p class=\"dialogue thomas-receiving-news\">—¿Qué fue esa explosión?</p>",
    "[HTML]<p class=\"dialogue communications-specialist\">—Señor... perdimos contacto con el equipo Alpha. Última transmisión de la Mayor Chen indicaba compromiso total de su unidad.</p>",
    "Thomas Kim miró las pantallas que mostraban una columna de humo elevándose desde la ubicación del equipo de reconocimiento.",
    "Treinta años de servicio militar le habían enseñado a reconocer el sonido de una granada de fragmentación a través de los sismógrafos.",
    "[HTML]<p class=\"dialogue thomas-grim-understanding\">—Chen eligió la muerte antes que la transformación.</p>",
    "[HTML]<p class=\"dialogue communications-follow-up\">—Señor, también estamos recibiendo informes de que las criaturas en otros sitios han... detenido sus actividades de construcción. Como si estuvieran... lamentando.</p>",
    "[P68]",
    "[LOC]Valle Oscuro - Catedral Central - 18:00 hrs",
    "En el corazón de la Catedral, Maya sintió la muerte de Sarah Chen como un dolor físico que le atravesó el pecho.",
    "Las voces que susurraban en su mente se habían quedado silenciosas por primera vez en días.",
    "—La primera guerra ha comenzado,",
    "susurró al aire vacío.",
    "—Ahora ambos lados han perdido sangre.",
    "A su alrededor, las estructuras óseas pulsaron con una luz más tenue, como si la propia catedral estuviera de luto.",
    "[HTML]<div class=\"parallel-scene-break\"><p class=\"location-marker\"><em>Centro de Comando - 18:30 hrs</em></p></div>",
    "Thomas Kim se encontró frente a frente con la realidad de lo que significaba liderar durante la primera guerra entre especies en la historia de la Tierra.",
    "Sarah Chen había sido una de sus mejores oficiales. Una mujer brillante que había elegido la muerte antes que entregar su humanidad.",
    "[HTML]<p class=\"dialogue thomas-memorial\">—Que se registre en los archivos militares que la Mayor Sarah Chen murió defendiendo el derecho fundamental de la humanidad a seguir siendo humana, sin importar el costo.</p>",
    "[HTML]<p class=\"dialogue thomas-resolve\">—Y que se registre también que su sacrificio no será en vano. Ahora sabemos que pueden ser heridos, que sienten pérdida, que no son invencibles.</p>",
    "Miró hacia las pantallas que mostraban las estructuras óseas ahora más quietas. Como si las entidades estuvieran procesando lo que había pasado.",
    "[HTML]<p class=\"final-observation\">La guerra había comenzado oficialmente. Y la primera baja había sido alguien que había elegido morir como humana antes que vivir como algo más.</p>",
    "[HTML]<p class=\"hook final-hook\">Pero mientras Thomas planificaba los próximos movimientos tácticos, no sabía que la muerte de Sarah Chen había hecho algo que ninguno de los dos bandos esperaba: había unido a ambas especies en el luto.</p>"
  ]
};
