const CAPITULO = {
  numero: 1,
  titulo: "Primera Sangre",
  paginas: "5-20",
  nav: {
    anterior: { href: "index.html", label: "← Índice" },
    siguiente: { href: "capitulo_02.html", label: "Capítulo 2 →" }
  },
  contenido: [
    "[P5]",
    "[LOC]Centro de Comando Conjunto, Seúl - 12 de octubre, 05:47 hrs\n        Día 4 desde las primeras desapariciones",
    "[OPEN]Maya Park llegaba al Valle Oscuro cuando las radios militares empezaron a fallar.",
    "Las radios crepitaron. Murieron. Una tras otra, en orden.",
    "En el bunker cinco pisos bajo tierra, el General Thomas Kim miró las pantallas. Los datos no tenían sentido.",
    "Las palabras salieron más secas de lo que había pretendido:",
    "—Coronel Park, ¿cuántas personas hemos perdido en las últimas setenta y dos horas?",
    "Su voz sonó extraña en el aire procesado del búnker. Algo esencial se había perdido en el filtrado.",
    "En las pantallas, lo que había sido el Valle de la Claridad ahora era una mancha gris que dolía de mirar.",
    "Valle de la Claridad. Siglos de monjes caminando senderos de grava, agua cristalina reflejando estatuas de Buda talladas en roca volcánica. El río Cheong donde los peces nadaban visibles entre piedras pulidas.",
    "Thomas había visitado el lugar una vez, hacía años—una excursión familiar cuando su hija tenía doce años. Recordaba el silencio sagrado, el aire que sabía a pino y agua pura. Hasta hace una semana.",
    "Ahora: Valle Oscuro. El nombre había surgido espontáneamente en las noticias. Doce desaparecidos. El verde vibrante se había vuelto gris ceniza, y el río ya no reflejaba el cielo.",
    "—Trece confirmadas desaparecidas, General. La más reciente hace seis horas. Los equipos de búsqueda y rescate reportan... dificultades técnicas cuando se acercan al perímetro interior.",
    "—¿Qué tipo de dificultades?",
    "—Fallas de equipos de comunicación, señores. GPS que muestra ubicaciones imposibles. Brújulas que apuntan hacia direcciones que... que no deberían existir.",
    "[P6]",
    "Los números en las pantallas se burlaban de él. Lecturas imposibles. Coordenadas que apuntaban a lugares inexistentes.",
    "La humillación pesó en su estómago. Sólida, sin salida. Treinta años de expertise y ahora miraba equipos que no sabía usar—esa era la verdad que no podía decirle a nadie.",
    "Terroristas, crisis políticas, desastres naturales—todo había tenido sentido antes. Reglas. Causas y efectos.",
    "Esto era diferente. Esto era estar desnudo frente a lo incomprensible.",
    "—Implementen perímetro de seguridad de cinco kilómetros. Nadie entra sin autorización directa de este comando.",
    "—Sí, señor. ¿Y qué hacemos con los civiles que ya están en el área?",
    "Thomas miró las pantallas una vez más. En una de ellas, una pequeña figura solitaria se movía hacia el centro del valle con lo que parecía ser equipo de grabación.",
    "—¿Quién es esa persona?",
    "—Trabajando en identificación, General.",
    "[HTML]<div class=\"parallel-scene-break\"><p class=\"perspective-shift\"><em>Al mismo tiempo, en un departamento de Gangnam, otra persona despertaba con sus propios demonios—</em></p><p class=\"location-marker\"><em>Departamento de Maya Park, Seúl - 05:30 hrs</em></p></div>",
    "[P7]",
    "[OPEN]5:30 AM. El mismo despertar brusco de siempre. No era disciplina—era que los sueños se habían vuelto insoportables después de las cinco horas. Ocho meses despertándose con el corazón martilleando y la certeza de que había algo importante que debía recordar, algo que se desvanecía como humo en cuanto abría los ojos.",
    "Jung-ho a los catorce años, preguntando por qué no había ido con él al río. Maya despertaba con la garganta cerrada y el sabor metálico de la culpa en la boca.",
    "Cinco minutos mirando las grietas del techo. El dolor era lo único tangible que le quedaba de Jung-ho.",
    "A los veintidós años, estudiante de último año de Antropología Cultural en la Universidad Yonsei, Maya había desarrollado una rutina: despertar temprano, revisar los comentarios de su canal de YouTube, desayunar con su madre, y decidir si quedarse en clases o investigar para su canal MinJung Oscura.",
    "La cocina: azulejos blancos, demasiado brillantes a esa hora.",
    "Su madre se movía por el espacio con los pasos cuidadosos que había desarrollado desde el funeral—como si caminar demasiado fuerte pudiera quebrar algo más de lo que ya estaba roto. La televisión murmuraba noticias que nadie escuchaba realmente.",
    "La mesa de madera todavía tenía las marcas del lápiz de Jung-ho—surcos donde había presionado demasiado fuerte mientras dibujaba esos patrones que nunca había explicado completamente.",
    "Maya pasó los dedos por las marcas. Braille de pérdida.",
    "—Maya-ya, comes muy poco últimamente —dijo la Sra. Park sin levantar la vista del arroz—. No es saludable para una estudiante universitaria.",
    "—Estoy bien, eomma.",
    "—Jung-ho siempre decía que comieras más. «Maya-noona está muy flaca», decía.",
    "Maya se detuvo a medio bocado. Ocho meses después, su madre aún hablaba de Jung-ho en presente. Como si fuera a entrar corriendo pidiendo dinero para el autobús.",
    "—Hoy voy a salir temprano de la universidad —dijo Maya, cambiando de tema—. Tengo que grabar un video para el canal.",
    "Su madre asintió vagamente. Nunca había entendido completamente qué era MinJung Oscura, pero sabía que mantenía a Maya ocupada. Y ocupada era mejor que como había estado los primeros meses después del accidente, cuando Maya no había podido levantarse de la cama durante semanas enteras, cuando había dejado de comer, de hablar, de reconocer que el mundo seguía girando alrededor de su pérdida.",
    "La casa—un apartamento de dos dormitorios en un edificio de ladrillo de cuatro pisos en el distrito de Gangnam—estaba en silencio.",
    "Su madre había aprendido a caminar más suave desde el funeral, sus pantuflas apenas susurrando contra el suelo de madera que Jung-ho solía recorrer corriendo cuando llegaba tarde a la escuela.",
    "Ambas habían desarrollado maneras de navegar alrededor del espacio que Jung-ho había ocupado: su silla en la mesa del comedor, el sofá donde se sentaba a ver televisión, el pasillo donde había colgado su mochila escolar.",
    "Como si su ausencia fuera un objeto físico que había que esquivar.",
    "El último bocado sabía a cartón.",
    "Maya besó a su madre en la mejilla—piel fría, más frágil que antes del funeral—y salió al mundo donde tenía que fingir que era una persona normal.",
    "Ocho meses de práctica. El dolor privado se quedaba en casa.",
    "Afuera, Maya Park era estudiante de último año, youtuber exitosa, hermana mayor responsable. Adentro, era un recipiente vacío caminando por movimientos automáticos.",
    "[P8]",
    "El teléfono ardía en sus manos mientras revisaba comentarios.",
    "La parada de la línea 9 la envolvió con su rutina predecible: diesel quemado en el aire, el vendedor del carrito azul—pintura descascarada, ruedas chirriantes—sirviendo café aguado a oficinistas zombis.",
    "Cuarenta y cinco minutos hasta Yonsei. Tiempo para hundirse en su otra vida, donde MinJung Oscura tenía respuestas que Maya Park no podía encontrar.",
    "Los números parpadeaban en la pantalla: 8,500 vistas en el último video, 850,000 suscriptores esperando revelaciones. Todos creyendo que ella sabía algo.",
    "La verdad era más simple: solo sabía hacer preguntas que dolían demasiado para ignorar.",
    "MinJung Oscura había crecido lentamente hasta alcanzar los 850 000 suscriptores gracias a su trabajo meticuloso investigando casos locales que la policía consideraba «inexplicables» o «cerrados sin resolución». Min por misterio, Jung por su hermano menor. Un nombre que llevaba el peso de ocho meses de preguntas sin respuesta.",
    "Y entonces un comentario la detuvo:",
    "[HTML]<p class=\"social-media-comment\"><em>\"Mi primo desapareció cerca de un río también. Las autoridades dijeron lo mismo: accidente. Pero había marcas extrañas en las piedras que nunca explicaron.\"</em></p>",
    "Marcas extrañas en las piedras. Las palabras se quedaron fijas. El mundo se tambaleó. De pronto podía oír la voz de Jung-ho otra vez: \"Las piedras están organizadas, noona. Como si alguien las hubiera puesto ahí.\"",
    "Los ojos se le cerraron por sí solos. El presente se desintegró—ruido del tráfico, calor matutino, olor a gasolina—todo borrado por la fuerza de la memoria. El dolor era un túnel temporal que la arrastraba de vuelta...",
    "[HTML]<div class=\"memory-transition\"><p><em>La mente la lleva ocho meses atrás—</em></p></div>",
    "[HTML]<div class=\"flashback-section\"><p class=\"location-marker flashback-marker\"><em>Casa de los Park - 8 meses atrás - 19:30 hrs</em></p><p class=\"transition-bridge\"><em>La cocina familiar. Jung-ho llegando tarde—algo inusual. La conversación que se convertiría en la última...</em></p></div>",
    "[P9]",
    "Jung-ho había llegado tarde a cenar, lo que era inusual. A los catorce años, era meticuloso con los horarios familiares, especialmente con las comidas que su madre preparaba.",
    "—¿Dónde estabas? —preguntó Maya cuando su hermano se sentó a la mesa.",
    "—En el río con mis amigos. Hay algo raro allí, Maya-noona.",
    "—¿Raro cómo?",
    "Jung-ho masticaba despacio—siempre lo hacía cuando pensaba, como si el proceso de comer lo ayudara a organizar ideas.",
    "Esa arruga entre las cejas que salía cuando se enfrentaba a un problema de matemáticas difícil, solo que esta vez no se trataba de matemáticas.",
    "Esta vez se trataba de algo que había visto y que no encajaba en su comprensión de cómo debería funcionar el mundo.",
    "—Las piedras están... organizadas. Como si alguien las hubiera puesto en patrones específicos. Y los peces no se acercan a esa área.",
    "—Tal vez algún estudiante de arte hizo una instalación —había sugerido Maya, sin darle mucha importancia.",
    "—No es arte, noona. Es más viejo que eso. Las piedras están medio enterradas, como si hubieran estado ahí por años. Décadas, tal vez.",
    "El cuaderno apareció sobre la mesa como siempre—Jung-ho no podía explicar cosas complejas sin dibujar.",
    "Sus manos se movían con precisión, trazando líneas que se cortaban en ángulos imposibles, círculos anidados como aros olímpicos desquiciados.",
    "Maya podía ver la intensidad en sus ojos—esa necesidad compulsiva de reproducir exactamente lo que había visto, como si los dibujos pudieran revelarle el significado que se le escapaba.",
    "—Maya-noona, ¿por qué alguien organizaría piedras así? No parece decorativo. Parece... funcional. Pero no sé para qué.",
    "El orgullo y el miedo se entrelazaron en el pecho de Maya como cables eléctricos tocando agua.",
    "Jung-ho demasiado brillante, demasiado curioso, demasiado dispuesto a meterse en problemas por responder preguntas que nadie más se hacía.",
    "Catorce años y ya pensaba como un investigador, buscando patrones donde otros niños solo verían piedras.",
    "La brillantez sin experiencia era peligrosa—útil y mortal al mismo tiempo.",
    "—¿Por qué preguntas eso, Jung-ho?",
    "—Es solo que... —Jung-ho dejó sus palillos y miró por la ventana hacia las montañas distantes—. Cuando estoy cerca de esas piedras siento como si hubiera algo importante que no estoy entendiendo. Como cuando sabes que te estás olvidando de algo, pero no recuerdas qué. Es molesto.",
    "El escalofrío empezó en la base del cuello y bajó despacio por los brazos. Las palabras de Jung-ho resonaron en un lugar profundo de su cerebro, en esa parte primitiva que reconoce el peligro antes de que la mente racional pueda procesarlo. Su hermano no estaba al borde de un precipicio—ya había saltado y solo le estaba contando lo que había visto durante la caída.",
    "—En antropología estudiamos cómo las culturas dejan marcas en el paisaje —dijo Maya, tratando de mantener un tono académico para calmar su propia ansiedad—. Es posible que lo que viste sean restos de algún asentamiento antiguo que no ha sido documentado oficialmente.",
    "—Jung-ho —le dijo Maya, con más seriedad de la que había usado con él antes—, prométeme que si encuentras algo que te haga sentir... extraño, me vas a llamar inmediatamente. Sin importar qué tan interesante sea, sin importar si crees que puedes manejarlo solo.",
    "—¿Por qué estás preocupada, noona?",
    "Cómo explicar que sus palabras habían encendido todas las alarmas en su cerebro. Cómo decirle que habían heredado la misma necesidad obsesiva de respuestas, pero que él la aplicaba a misterios del presente mientras ella se escondía en culturas muertas y seguras. Cómo advertirle que algunas preguntas eran peligrosas sin sonar como una hermana mayor paranoica. Las palabras se atascaron en su garganta.",
    "—Solo... prométemelo.",
    "—Te lo prometo, Maya-noona.",
    "—Y mañana voy a ir otra vez. Quiero tomar fotos para tu canal. Tal vez tú puedas averiguar qué significa todo esto.",
    "Esa fue su última conversación real. Fue una promesa que Jung-ho nunca tuvo la oportunidad de cumplir. Maya nunca supo si había tomado las fotos, pero sabía que había ido al río solo, a pesar de su promesa, y que algo allí había cambiado el curso de sus vidas para siempre.",
    "Ahora, ocho meses después, Maya recordaba cada palabra. Entonces había sido solo una cena familiar más. No sabía que era su última oportunidad de proteger a Jung-ho.",
    "[P10]",
    "Tres días después, Maya recibió la llamada que partió su vida en dos: antes de Jung-ho y después de Jung-ho.",
    "Había estado en la universidad cuando sonó su teléfono. La voz del oficial fue profesional, cuidadosa, entrenada para entregar la peor noticia posible de la manera menos traumática. \"Señorita Park, necesitamos que venga a identificar un cuerpo.\" Pero ninguna cantidad de entrenamiento en comunicación de crisis podía suavizar la realidad de que su hermano menor había sido encontrado en el río, ahogado, según el reporte oficial.",
    "Pero fue el día después del funeral, cuando Maya finalmente reunió el valor para visitar el lugar donde habían encontrado el cuerpo de Jung-ho, cuando todo cambió. Necesitaba verlo por sí misma, necesitaba entender qué había visto su hermano que lo había perturbado tanto.",
    "Cuando Maya vio el área donde habían encontrado a Jung-ho comprendió que Jung-ho había tenido razón. Las piedras formaban un semicírculo perfecto alrededor del lugar donde encontraron su cuerpo.",
    "El detective Park (sin relación familiar) había sido amable pero claro cuando Maya fue a la estación de policía:",
    "—Señorita Park, entiendo su dolor, pero su hermano se resbaló y cayó al agua. El área es conocida por ser peligrosa, especialmente de noche.",
    "—¿Pero las piedras? Jung-ho mencionó que estaban organizadas de manera extraña.",
    "—Los adolescentes a veces ven patrones donde no los hay. Es natural buscar significado en tragedias aleatorias.",
    "—¿Y qué hay del hecho de que Jung-ho sabía nadar perfectamente? Era el mejor nadador de su clase.",
    "—Los ríos de montaña son impredecibles, señorita Park. Corrientes subterráneas, temperatura del agua, rocas resbalosas... incluso los mejores nadadores pueden tener problemas.",
    "Maya había aceptado la explicación porque no tenía alternativa legal, porque el sistema requería que aceptara la versión oficial para poder continuar con los trámites del funeral, los papeles, todas las tareas administrativas que la muerte requiere. Pero nunca la había creído completamente. En las noches, cuando no podía dormir, repasaba cada detalle de la conversación final con Jung-ho, buscando señales que había pasado por alto, palabras que debería haber interpretado como advertencias.",
    "Y cuando encontró los dibujos de Jung-ho dos meses después, enterrados entre sus tareas escolares como si fueran notas de una clase, supo que había tenido razón en dudar desde el principio.",
    "Había sido un sábado por la mañana. Maya estaba ayudando a su madre a limpiar el cuarto de Jung-ho—una tarea que habían estado posponiendo desde el funeral porque era demasiado dolorosa. Mientras empacaba sus libros escolares para donarlos, un cuaderno de matemáticas se abrió en sus manos, y varios papeles sueltos cayeron al suelo.",
    "[P11]",
    "Los dibujos estaban en su cuaderno de matemáticas, entre problemas de álgebra y ecuaciones de geometría: patrones complejos que Jung-ho había estado copiando de memoria. Debajo, con su letra cuidadosa y meticulosa, había escrito: \"Piedras del río - ¿qué son? ¿para qué sirven?\"",
    "Maya había llevado los dibujos al departamento de antropología de la Universidad Yonsei, ubicado en el quinto piso del edificio de Humanidades—un complejo de ladrillo rojo con ventanales altos que se alzaba entre los árboles de ginkgo del campus. La oficina de la profesora Kim estaba atestada de libros apilados desde el suelo hasta el techo, artefactos de culturas antiguas dispuestos sobre cada superficie disponible, y mapas arqueológicos que cubrían las paredes como papel tapiz académico.",
    "—¿Son símbolos conocidos? —preguntó a la profesora Kim, su asesora de tesis, mientras extendía los dibujos sobre el escritorio de madera lleno de cicatrices que había visto décadas de estudiantes nerviosos presentando proyectos.",
    "La profesora estudió los dibujos con la dedicación de años, ajustándose las gafas de lectura que colgaban de una cadena dorada alrededor de su cuello.",
    "—Son... intrigantes, Maya. Parecen patrones de algunas culturas prehistóricas, pero no específicamente coreanas. Los círculos concéntricos y las intersecciones angulares aparecen en varios sitios arqueológicos mundiales, pero nunca en esta combinación específica. ¿Dónde los encontraste?",
    "—Mi hermano los dibujó antes de... antes de su accidente. Los vio en un río.",
    "—¿Tu hermano estudiaba arqueología?",
    "—No. Estaba en segundo de preparatoria. Pero siempre fue observador. Tenía ojo para detalles que otros no notaban.",
    "La profesora devolvió los dibujos con una expresión pensativa.",
    "—Si estos patrones realmente aparecieron de forma natural en un río, sería muy inusual, Maya. Los patrones geológicos rara vez forman diseños tan... deliberados. Y si fueron hechos por humanos, representan un nivel de planificación y conocimiento geométrico que sugiere una cultura más sofisticada de lo que se supone existió en esta región en períodos antiguos.",
    "[P12]",
    "Esa noche, Maya se sentó frente a su computadora con los dibujos de Jung-ho extendidos sobre su escritorio y sintió algo que no había sentido en meses: propósito.",
    "No era solo dolor ahora. Era dolor con dirección. Si las autoridades no iban a buscar respuestas, si el sistema consideraba que la muerte de Jung-ho era suficientemente explicada con la palabra «accidente», entonces ella encontraría sus propias respuestas. Y las compartiría, para que otros que habían perdido a alguien en circunstancias «inexplicables» supieran que no estaban solos en sus dudas.",
    "—MinJung Oscura —murmuró, probando cómo sonaba. Min por misterio, Jung por su hermano—. Un nombre para las preguntas sin respuesta. Un lugar donde las preguntas incómodas pueden ser hechas sin disculpas.",
    "Su primer video fue sobre Jung-ho, naturalmente. Pero no lo presentó como paranormal o sobrenatural. Lo presentó como lo que era: un caso de muerte accidental que tenía algunos elementos que no habían sido explicados satisfactoriamente.",
    "—No estoy diciendo que pasó algo misterioso —dijo a la cámara, sentada en su cuarto con los dibujos de Jung-ho extendidos sobre su escritorio—. Solo estoy diciendo que hay preguntas que merecen respuestas mejores que «Estas cosas pasan». Cuando perdemos a alguien, especialmente a alguien joven, merecemos entender no solo qué pasó, sino por qué.",
    "El video obtuvo trescientas visualizaciones. Dieciséis comentarios. Tres de ellos de personas que habían perdido familiares en circunstancias similares: muertes accidentales cerca de cuerpos de agua, con detalles extraños que las autoridades no habían considerado relevantes.",
    "Maya leyó cada comentario tres veces. Aquellas tres personas—extraños completos en internet—le habían dado algo que los profesionales del duelo, los psicólogos, y hasta su propia familia no habían podido darle: la confirmación de que no estaba loca por dudar, que no estaba siendo «dramática» al pensar que había más en la historia de lo que les habían dicho.",
    "Ese fue el inicio de MinJung Oscura. Un canal dedicado a hacer las preguntas que otros consideraban demasiado dolorosas o demasiado complicadas para valer la pena. Un lugar donde el dolor podía convertirse en investigación, donde las pérdidas podían convertirse en propósito.",
    "Ocho meses después, el canal había crecido hasta casi un millón de suscriptores. Pero para Maya, cada video seguía siendo fundamentalmente el mismo: una manera de seguir conversando con Jung-ho, de continuar la investigación que él había comenzado con sus preguntas incómodas y sus dibujos meticulosos.",
    "[HTML]<div class=\"flashback-end\"><p class=\"memory-break\"><em>El recuerdo se desvanece. El dolor la devuelve al presente—</em></p><p class=\"location-marker present-marker\"><em>Presente - Parada de autobús - 06:45 hrs</em></p></div>",
    "El teléfono todavía caliente en las manos. La parada de autobús real, concreta. Pero ahora los dibujos de Jung-ho tenían un nuevo significado.",
    "[P13]",
    "Maya había estado siguiendo los reportes sobre las desapariciones en el Valle Oscuro durante una semana. Oficialmente, las autoridades lo llamaban «eventos de búsqueda y rescate complejos». Extraoficialmente, los reporteros hablaban de «anomalías inexplicadas».",
    "Lo que había captado su atención no fueron las desapariciones en sí. En ocho meses de investigar casos inexplicados, había aprendido que las desapariciones, por trágicas que fueran, usualmente tenían explicaciones mundanas: accidentes, suicidios, decisiones personales de desaparecer. Lo que la intrigó fueron las fotografías.",
    "Un blogger independiente había publicado imágenes del área antes de que las autoridades cerraran el acceso al público. En una de las fotos, Maya vio algo que la hizo levantarse abruptamente de su asiento en el autobús.",
    "[HTML]<p><strong>Piedras. Organizadas en patrones. Patrones que reconoció.</strong></p>",
    "Maya se bajó del autobús en la siguiente parada—frente a un edificio de oficinas de cristal que reflejaba las nubes grises del cielo matutino—sin importarle que estuviera a diez cuadras de la universidad. Caminó rápido por las calles abarrotadas del distrito de Gangnam, esquivando salarymen con trajes oscuros que caminaban con la misma urgencia robótica que ella había desarrollado en los últimos ocho meses. Los rascacielos de acero y vidrio se alzaban a ambos lados como guardianes impersonales de una ciudad que nunca dormía completamente.",
    "El trayecto de regreso a casa la llevó por las mismas calles familiares que había recorrido con Jung-ho cientos de veces: la panadería donde compraban pasteles de crema después de la escuela, la tienda de conveniencia donde Jung-ho siempre pedía permiso para comprar snacks, el cruce donde había tenido que tomarlo de la mano porque era demasiado impaciente para esperar la luz verde. Una vez en casa, corrió a su cuarto y sacó el cuaderno de Jung-ho del cajón donde lo guardaba como si fuera un objeto sagrado. Abrió su laptop y amplió la fotografía del Valle Oscuro hasta que pudo ver claramente las formaciones rocosas.",
    "No eran idénticos a los dibujos de Jung-ho, pero eran... relacionados. Como si fueran parte del mismo lenguaje visual. Como si hubieran sido creados por la misma mano, o siguiendo las mismas reglas.",
    "[P14]",
    "Maya se quedó mirando la pantalla durante diez minutos. Los patrones eran similares, sí. Pero eso no significaba nada concreto. Podían ser coincidencia. Podían ser formaciones naturales que se repetían.",
    "Pero también podrían no serlo.",
    "Se mordió el labio inferior, un hábito que había desarrollado cuando estaba nerviosa. Trece personas habían desaparecido en el Valle Oscuro. Las autoridades habían cerrado el acceso. Era peligroso.",
    "Abrió una nueva pestaña en su navegador y buscó «Valle Cheongmyeong desapariciones». Los artículos eran vagos, llenos de eufemismos. «Eventos de búsqueda y rescate complejos.» «Dificultades técnicas.» «Se recomienda evitar el área.»",
    "Maya cerró la laptop y se levantó. Caminó a la cocina, sirvió un vaso de agua, lo bebió lentamente. Su madre estaba viendo un drama en televisión en la sala.",
    "¿De verdad estaba considerando ir? ¿Sola? ¿A un lugar donde la gente desaparecía?",
    "Regresó a su cuarto y abrió la laptop otra vez. Amplió la fotografía todo lo que pudo. Los patrones estaban ahí. Jung-ho los había dibujado ocho meses antes de que el Valle Oscuro existiera como concepto público.",
    "Tomó el cuaderno de Jung-ho y lo puso junto a la pantalla. Similar, no idéntico. Pero definitivamente relacionado.",
    "Maya se quedó inmóvil durante cinco minutos, mirando los dibujos. Luego tomó su teléfono y buscó los números de transporte público al Valle Cheongmyeong. Dos horas en tren, luego autobús local. Si salía ahora, podría estar de vuelta antes del anochecer.",
    "Si. Gran si.",
    "Buscó en YouTube «Valle Oscuro investigación». Encontró tres videos de bloggers locales. Todos filmados desde el perímetro exterior, todos con títulos sensacionalistas, ninguno realmente informativos. Los comentarios estaban llenos de teorías conspirativas y advertencias.",
    "Revisó su cuenta bancaria. Tenía suficiente para el transporte y algo de comida. Su cámara estaba cargada. Tenía memoria de sobra en las tarjetas.",
    "La parte racional de su mente le gritaba que era una estupidez. Que podía perderse como los otros trece. Que su madre ya había perdido un hijo.",
    "La otra parte—la parte que había estado despierta desde las 5:30 AM durante ocho meses—le susurraba que esta podría ser la única oportunidad real de entender qué le había pasado a Jung-ho.",
    "Empacó una mochila pequeña: cámara, lentes extra, baterías portátiles, una botella de agua, barras de granola. Escribió una nota: \"Salgo a grabar un video. Regreso antes de las 8 PM. Te amo.\"",
    "No mencionó el Valle Oscuro. Su madre no necesitaba esa preocupación adicional.",
    "En el tren, Maya revisó su teléfono cada cinco minutos. Le mandó su ubicación a una amiga con el mensaje: \"Si no respondo después de las 8 PM, llama a la policía.\" Lo pensó dos veces y borró el mensaje sin enviarlo.",
    "Quizás debería haber traído a alguien. Pero ¿a quién? Sus amigos pensarían que estaba loca. Y tal vez tenían razón.",
    "[HTML]<div class=\"parallel-scene-break\"><p class=\"perspective-shift\"><em>A esa misma hora, en el lado opuesto de la ciudad—</em></p><p class=\"location-marker\"><em>Laboratorio de Bioquímica Forense, Universidad Yonsei - 11:30 hrs</em></p></div>",
    "La Dra. Sophie Yun anotó los resultados y los volvió a leer dos veces.",
    "[HTML]<p>Las muestras de tejido provenían del Valle Oscuro. Suelo, líquido orgánico, fragmento de material óseo sin clasificar. Las había recibido esa mañana de un contacto en el departamento forense del distrito, con una sola línea escrita a mano: <em>nadie sabe qué hacer con esto</em>.</p>",
    "Los números no tenían sentido. La secuenciación mostraba proteínas que no correspondían a ninguna especie registrada. La densidad mineral del fragmento óseo excedía cualquier tejido humano conocido en un cuarenta por ciento.",
    "Error de calibración. Sophie limpió los electrodos, reinició el analizador y corrió la muestra otra vez.",
    "Los mismos números.",
    "Marcó los resultados como inconcluyentes, cerró el archivo y empujó las muestras al fondo del estante de pendientes. Había una explicación técnica. Siempre la había.",
    "[HTML]<div class=\"parallel-scene-break\"><p class=\"perspective-shift\"><em>Mientras Maya viajaba hacia el Valle Oscuro, en el bunker subterráneo—</em></p><p class=\"location-marker\"><em>Centro de Comando Conjunto - 14:20 hrs</em></p></div>",
    "[P15]",
    "—General Kim —llamó el Teniente Park desde su consola—. Tenemos actividad civil en el perímetro del Valle Oscuro.",
    "Thomas Kim se acercó a las pantallas. Los drones de reconocimiento mostraban una figura solitaria cerca del área que había sido restringida apenas dos horas antes.",
    "—Parece ser una mujer joven. Está... grabando video.",
    "Kim frunció el ceño. En treinta años de carrera militar, había aprendido a confiar en sus instintos sobre cuándo algo estaba a punto de salirse de control.",
    "—¿Cómo pasó los controles de seguridad?",
    "—Señor, el perímetro se estableció hace solo dos horas. Es posible que ya estuviera en el área cuando implementamos las restricciones.",
    "En la pantalla, Maya Park ajustaba su cámara con precisión. Sus movimientos eran deliberados, profesionales. No parecía perdida o confundida.",
    "—¿Tenemos identificación?",
    "—Trabajando en ello, señor. Análisis facial en proceso.",
    "[P16]",
    "Kim observó cómo la figura se movía con propósito hacia el centro del valle. No como alguien que había tropezado accidentalmente con un área restringida, sino como alguien que tenía una razón específica, personal, para estar exactamente ahí.",
    "El perímetro debería haberse establecido seis horas antes. Eso era lo que dictaba el protocolo de emergencia civil, sección cuatro, párrafo dos. Kim lo sabía. También sabía que cada hora de retraso en ese tipo de decisiones existía porque alguien, en algún punto de la cadena de mando, había pagado el costo de actuar demasiado pronto. Los procedimientos no eran arbitrarios. Eran cicatrices institucionalizadas.",
    "—Mantengan vigilancia continua. Y si se acerca demasiado al área de las anomalías... —Kim se detuvo. En treinta años de servicio militar, nunca había dado órdenes sobre cómo manejar «anormalías». Sus manuales de protocolo no incluían secciones sobre fenómenos que desafiaban las leyes físicas conocidas.",
    "—Señor, ¿cuáles son las órdenes si entra en la zona de mayor actividad anómala?",
    "Kim miró la pantalla una vez más. La mujer había comenzado a hablar a su cámara, claramente grabando algún tipo de reportaje o documentación. Sus gestos eran los de alguien acostumbrada a explicar cosas complejas a una audiencia.",
    "—Por ahora, solo observamos. Y documentamos todo lo que pase.",
    "No sabía que acababa de tomar la decisión que cambiaría el curso de los eventos. Si hubiera enviado fuerzas para interceptar a Maya Park en ese momento, si hubiera establecido el perímetro de seguridad seis horas antes, si hubiera clasificado el área como zona de exclusión total, ella nunca habría llegado al centro del valle.",
    "Nunca habría desaparecido.",
    "Y nunca habría regresado como algo más de lo que había sido cuando se fue.",
    "[P17]",
    "[HTML]<div class=\"location-transition\"><p class=\"journey-bridge\"><em>Mientras Thomas Kim tomaba la decisión que cambiaría todo, Maya llegaba al corazón del misterio—</em></p><p class=\"location-marker\"><em>Valle Oscuro - Centro - 14:45 hrs</em></p></div>",
    "Cuarenta minutos de caminar y el mundo se había vuelto sordo. Ni insectos, ni pájaros, ni siquiera el susurro del viento en las hojas. Los pasos de Maya resonaban obscenos en el silencio. El aire no se movía—se sentía espeso, como si hubiera demasiado oxígeno o muy poco. Algo estaba mal en la composición básica de este lugar.",
    "Las estatuas de Buda. Algo estaba terriblemente mal con sus caras. Maya sacó el teléfono con dedos repentinamente torpes, comparó con las fotos turísticas que había guardado. En las imágenes: rostros serenos, sonrisas compasivas talladas en piedra volcánica. Aquí: expresiones torturadas, como si el sufrimiento hubiera crecido desde adentro de la roca. La piedra no podía cambiar. La piedra no tenía músculos para contraer. Pero ahora las estatuas parecían estar gritando en silencio.",
    "Alucinación. Tenía que ser alucinación. Ocho meses de duelo, falta de sueño, estrés. La mente creaba patrones donde no existían. Pero la cámara no alucina y la cámara mostraba lo mismo: caras de piedra deformadas por agonía que no debería ser posible.",
    "Ahí estaban. Los círculos concéntricos de Jung-ho, pero amplificados, magnificados, como si alguien hubiera tomado los dibujos de su hermano y los hubiera construido a escala arquitectónica. Piedras negras del tamaño de automóviles, organizadas en patrones que lastimaban los ojos. El aire alrededor de las piedras parecía denso, como gelatina invisible. Respirar cerca de ellas requiería esfuerzo consciente.",
    "La cámara pesaba como plomo en manos que no podían dejar de temblar. Maya había venido hasta aquí. Había ignorado todas las advertencias, todos los instintos, todos los síntomas de que este lugar estaba mal de maneras fundamentales. Lo mínimo que podía hacer era documentar por qué Jung-ho había tenido razón al tener miedo.",
    "—Hola —la palabra explotó en el aire muerto y rompió el silencio—. Estoy en el Valle Cheongmyeong —susurró, porque hablar en voz normal parecía blasfemia en este silencio—. Hay algo... Los patrones de piedras son idénticos a los dibujos de Jung-ho.",
    "Y entonces la sensación la golpeó: reconocimiento. No déjà vu—algo más primitivo y aterrador. Como si este lugar conociera su nombre. Como si las piedras hubieran estado esperando que llegara, como si hubiera tenido una cita programada con lo imposible. Su cuerpo reconocía este lugar de maneras que su mente se negaba a aceptar.",
    "—Los patrones de piedra que ven aquí son extraordinariamente similares a dibujos que mi hermano menor hizo antes de su muerte —continuó, mostrando el cuaderno de Jung-ho a la cámara—. Si hay una conexión, podría significar que hay un patrón más amplio de lo que inicialmente pensé.",
    "Un paso hacia las piedras centrales. Los grabados emergieron—símbolos quemados en la roca por algo que no era humano. Maya sacó el cuaderno de Jung-ho. Idénticos. Su hermano había estado aquí antes que ella.",
    "De rodillas sobre tierra demasiado tibia. Los símbolos dolían de mirar—cada línea era una aguja en el cerebro. Pero no podía apartar la vista.",
    "[P18]",
    "—Los grabados son... muy antiguos —murmuró a la cámara, tratando de sonar profesional pero notando que le temblaba un poco la voz—. No corresponden a ninguna cultura coreana conocida. Los patrones son...",
    "Un crujido. Hojas secas. Algo se movía en el bosque.",
    "Maya se incorporó rápidamente, el corazón latiéndole fuerte. Probablemente un animal. Un ciervo. Tal vez por eso no había otros sonidos—había un depredador en la zona.",
    "Pero cuando levantó la vista, lo que vio la paralizó completamente.",
    "Algo entre los árboles.",
    "No—alguien.",
    "Tres metros de altura.",
    "Esqueleto caminando.",
    "Huesos blancos fosforescentes.",
    "Esto no existía.",
    "Los pulmones se cerraron.",
    "El aire se volvió sólido.",
    "Error de sistema.",
    "Esto no computaba.",
    "Y tenía ojos.",
    "Cuencas brillando como brasas azules.",
    "La estaba mirando.",
    "—No, no, no, no —las palabras salieron como letania—. Esto no está pasando.",
    "[HTML]<p class=\"maya-internal-panic\"><em>Jung-ho tenía razón. Jung-ho vio esto. Por eso está muerto. Ahora yo también voy a morir.</em></p>",
    "CORRER. La palabra explotó en su cerebro como sirena de emergencia.",
    "[HTML]<p class=\"maya-panic-thoughts\"><em>Salir de aquí. Nunca debería haber venido sola. Mamá me va a matar—si es que sobrevivo.</em></p>",
    "Pero las piernas no respondían. El terror las había convertido en cemento.",
    "La mano—si es que eso era una mano—se alzó hacia ella. Dedos como lápices de hueso, articulados en demasiados lugares. Cinco dedos que se extendían y extendían hasta ser garras de marfil que podían envolver su cabeza completa.",
    "El grito salió desde un lugar más profundo que los pulmones, más primitivo que el miedo—el sonido que hace una presa cuando sabe que va a morir.",
    "[P19]",
    "Hiperventilación.",
    "El mundo se pixeló en los bordes.",
    "Manos empapadas en sudor.",
    "La cámara resbaló.",
    "[HTML]<p class=\"maya-denial-thoughts\"><em>Alucinación. Colapso nervioso.</em></p>",
    "Pero se veía real.",
    "Pero seguía AHÍ. Las piedras eran reales. El cuaderno de Jung-ho era real. La muerte de su hermano era real. Esto también.",
    "Y se movía. Hacia ella. Un paso que no hizo ruido, otro que violó las leyes de la física porque algo tan grande no podía moverse tan silenciosamente.",
    "—Si alguien ve esto —Maya apenas logró susurrar a la cámara, su voz quebrada por el pánico—, no vengan aquí. Hay algo... hay algo que no debería existir.",
    "Flotaba.",
    "Los pies no tocaban el suelo.",
    "Sin sonido.",
    "Sin respiración.",
    "Caminando hacia ella.",
    "El hechizo se quebró. Las piernas respondieron. Maya corrió como si el mundo se estuviera acabando—porque quizás sí se estaba acabando.",
    "Tropezó con las piedras. Rodilla sangrando contra los jeans. Levantarse. Seguir corriendo.",
    "—Jung-ho, perdóname —jadeó mientras corría—. No te creí. Debería haberte creído.",
    "La cámara seguía grabando, golpeando contra sus costillas. Sus sollozos resonaban disonantes en el silencio antinatural del valle.",
    "Diez metros.",
    "Cinco.",
    "Casi en el borde del bosque—",
    "El mundo se cortó como televisión apagándose.",
    "Silencio."
  ]
};
