const CAPITULO = {
  numero: 0,
  titulo: "Los Primeros Susurros",
  paginas: "1-4",
  nav: {
    anterior: { href: "index.html", label: "← Índice" },
    siguiente: { href: "capitulo_01_nuevo.html", label: "Capítulo 1 →" }
  },
  contenido: [
    "[P1]",
    "[LOC]Valle Cheongmyeong - 9 de octubre - 04:30 hrs\n        Día 1",
    "[OPEN]Daniel Kim llevaba cuarenta y dos años despertando antes del amanecer. Café negro, revisión del clima, inspección de los campos. Ese orden nunca fallaba. Esa mañana, antes de abrir los ojos, algo era diferente.",
    "La vibración empezó en el fémur derecho. No era dolor—era reconocimiento. Cada hueso despertando en secuencia, como si hubieran estado esperando una señal que tardó décadas en llegar.",
    "Se quedó inmóvil en la cama. Sus manos, a la primera luz del amanecer que se filtraba por las persianas de madera, se veían normales. Pero debajo de la piel, algo se desplazaba.",
    "Hannah estaba parada en el umbral. Ocho años, ropa de dormir, pies descalzos sobre el suelo frío. Había venido a buscar el desayuno de siempre.",
    "—Abuelo, tus manos.",
    "Daniel las miró. El metacarpo derecho estiraba la piel desde adentro, empujándola hacia afuera con la precisión de algo que sabía exactamente adónde iba. Sin prisa. Sin dolor.",
    "—Hannah, llama a—",
    "La clavícula se movió. No se rompió. Decidió otra posición.",
    "La sensación no era dolor. Era completar algo que llevaba décadas incompleto.",
    "—¡AHORA! —gritó Daniel. Algo que nunca había hecho en sesenta y siete años.",
    "La niña corrió.",
    "[P2]",
    "[LOC]Granja Daniel Kim - 10 de octubre - 06:15 hrs\n        Día 2",
    "El agente Henry Lee llegó antes que su superior. Primer mes de servicio. Nunca había vomitado en una escena del crimen.",
    "Esa mañana vomitó.",
    "Encontraron a Daniel Kim en el campo de arroz tres días después. Brazos extendidos, piel adherida directamente al hueso. En el cuello y las muñecas, agujeros perfectamente circulares, cada uno del diámetro exacto de una moneda. Sin sangre en el suelo. Sin rastro de lucha.",
    "El Sargento Choi llegó siete minutos después. Examinó los agujeros en silencio durante cuarenta segundos. Luego se limpió las manos en los pantalones.",
    "—¿Qué fue esto? —preguntó Henry.",
    "—Perro salvaje. Eso es lo que reportas.",
    "—Sargento, los agujeros son perfectamente circulares. Un perro no—",
    "—Perro salvaje. Punto final.",
    "Henry asintió. Cuando Choi se dio vuelta para llamar al forense, sacó el teléfono y fotografió las marcas. No sabía por qué lo hacía. Solo sabía que no quería ser el único que recordara que eso había existido.",
    "[P3]",
    "[LOC]Corea del Sur — Días 2 y 3",
    "Los rumores viajaron más rápido que los reportes oficiales.",
    "En los mercados de Daegu, las abuelas hablaban de los «comedores de médula». En los bares nocturnos de Seúl circulaba el nombre de una sustancia callejera—polvo de hueso—que supuestamente hacía ver ciudades construidas antes que los dinosaurios. En los hospitales del distrito empezaron a llegar pacientes rascándose la piel, jurando que algo crecía debajo. Las radiografías mostraban estructuras óseas en lugares donde no debería existir ninguna.",
    "Las autoridades lo clasificaron como histeria colectiva.",
    "[P4]",
    "[LOC]Laboratorio Forense, Seúl - 11 de octubre\n        Día 3",
    "La Dra. Jennifer Park no había dormido en cuarenta horas.",
    "Las muestras de hueso provenientes del Valle Cheongmyeong no correspondían a ninguna especie registrada. La densidad superaba cualquier tejido humano conocido en un cuarenta por ciento. Y el ADN—el ADN era lo que la mantenía despierta.",
    "—Secuencias tricatenarias —murmuró a su grabadora—. Tres cadenas en lugar de dos. Y los marcadores de antigüedad no tienen sentido. Estos fragmentos tienen información genética anterior a cualquier forma de vida compleja conocida en la Tierra.",
    "Cerró el archivo. Lo abrió otra vez. Los números no cambiaron.",
    "Redactó el reporte clasificado con manos que no terminaban de estabilizarse. Lo envió a la línea militar directa con una sola línea al final, fuera del formato estándar:",
    "[HTML]<p class=\"document-warning\"><em>Este ADN no es terrestre.</em></p>",
    "[HOOK]El reporte llegó al Centro de Comando Conjunto la mañana del día 4. El General Thomas Kim lo leyó dos veces antes de levantar el teléfono."
  ]
};
