const CAPITULO = {
  numero: 5,
  titulo: "La Sangre Recordada",
  paginas: "37-44",
  nav: {
    anterior: { href: "capitulo_04.html", label: "← Capítulo 4" },
    siguiente: { href: "capitulo_06.html", label: "Capítulo 6 →" }
  },
  contenido: [
    "[P37]",
    "[OPEN]La Dra. Sophie Yun estaba en su octavo mes de embarazo cuando su sangre comenzó a brillar.",
    "Trabajaba tarde en su laboratorio de genética en la Universidad Yonsei, analizando muestras del extraño polen que aparecía por Seúl tras los eventos del Valle Oscuro.",
    "Sophie se especializaba en ADN mitocondrial —material genético heredado exclusivamente de las madres—. Había visto cosas extrañas: mutaciones inexplicables, secuencias genéticas que no coincidían con ningún patrón evolutivo conocido.",
    "Material genético que desafiaba toda lógica evolutiva.",
    "Pero nunca había visto su propia sangre responder a una muestra. Atraída. Sin razón medible.",
    "La gota de sangre de su control rutinario se movía por la placa de vidrio, dejando un rastro dorado que pulsaba con la misma luz enfermiza del valle.",
    "Cuando se acercó al polen, ambas sustancias resonaron emitían un sonido musical dimensional —frecuencias imposibles en materiales orgánicos normales—.",
    "—Esto es imposible,",
    "Susurró. Apartó los ojos de la placa y los fijó en la pared en blanco frente a ella.",
    "Su madre había muerto con todos los resultados en orden. Glucosa normal. Presión normal. Hemoglobina dentro del rango. Sophie tenía diecinueve años y los había revisado tres veces, convencida de que los médicos habían fallado en medir algo. Que había una cifra escondida en alguna parte que lo explicaba todo. Que si seguía buscando, encontraría el número que salvaría a su madre.",
    "No había ningún número. Solo el silencio del hospital a las cuatro de la mañana.",
    "La gota de sangre dorada pulsó sobre la placa de vidrio. Real. Completamente real. Sin ningún marco teórico que la contuviera.",
    "Sophie se llevó los dedos a la sien y presionó.",
    "Colocó las manos temblorosas sobre su vientre abultado. El corazón se le aceleraba.",
    "Su bebé había estado inquieto los últimos días, moviéndose constantemente, respondiendo a algo imperceptible para ella.",
    "[HOOK]Su teléfono sonó. El identificador de llamadas mostraba un número que no reconocía, pero sabía que debía contestar.",
    "[P38]",
    "—Dra. Yun, soy el General Thomas Kim. Necesito que venga al Centro de Comando inmediatamente. Es sobre su investigación genética... y sobre usted.",
    "—No entiendo. ¿Cómo conoce mi trabajo?",
    "—Doctora, está en nuestra lista. Una de las 2,847 descendientes directos.",
    "El teléfono se le resbaló de las manos. Los 2,847. Había escuchado ese número en noticias fragmentarias del valle.",
    "Nunca imaginó estar relacionada con él.",
    "—¿2,847 qué?",
    "Preguntó, recuperando el teléfono con manos incontrolables, resbaladizo por el sudor.",
    "—Descendientes, doctora. Portadores de material genético latente, patrones que han permanecido inactivos en ciertas líneas familiares durante milenios. Su sangre contiene secuencias que nuestros científicos denominan 'ADN sombra' —información genética que fue insertada artificialmente hace aproximadamente 230 millones de años por entidades que precedieron a la vida compleja en la Tierra. Y con los eventos actuales, esas secuencias se están... despertando.",
    "Sophie miró la muestra brillante, luego su reflejo en la ventana.",
    "Sus ojos, siempre marrones oscuros, ahora tenían motas doradas que pulsaban al ritmo de sus latidos.",
    "[P39]",
    "Mientras Sophie luchaba por comprender estas palabras imposibles en su laboratorio de la Universidad Yonsei, a cincuenta kilómetros de distancia, Jonathan y Miguel estaban enfrentando su propia transformación de una manera mucho más directa y violenta.",
    "La criatura que había hablado en español perfecto ahora estaba a menos de diez metros de su posición, acompañada por otras tres entidades esqueléticas.",
    "Jonathan mantenía su rifle apuntado, pero sus manos temblaban —no de miedo, sino de algo que lo aterrorizaba más—. Reconocimiento. Su corazón latía tan fuerte que estaba seguro de que las criaturas podían escucharlo.",
    "—Miguel, ¿sientes eso?",
    "Susurró sin apartar la vista de las criaturas.",
    "—Sí. Como si... como si las conociera. Como si hubieran estado esperándonos.",
    "[HTML]<p class=\"skeleton-sighting\">La criatura principal se acercó otro paso. Su estructura ósea era magnificente y terrible al mismo tiempo: huesos de marfil que reflejaban la luz de la luna, articulaciones que se movían con una gracia imposible —cada movimiento era exacto, sin desperdicio—, una presencia que irradiaba eones de sabiduría y dolor —billones de años de experiencia acumulada—. Cuando habló, su voz resonó tanto en el aire como directamente en sus mentes.</p>",
    "[HTML]<p class=\"dialogue latin-inscription\">—Nosotros también os hemos estado esperando, hermanos. Durante 230 millones de años hemos esperado a que despertarais.</p>",
    "Sin previo aviso, Jonathan bajó su arma.",
    "No fue una decisión consciente; sus brazos dejaron de obedecerle, algo más profundo que su voluntad había tomado el control —una parte ancestral de su mente había despertado—.",
    "[HOOK]\"Jon, ¿qué estás haciendo?\" Miguel gritó, pero incluso mientras hablaba, podía sentir la misma compulsión tirando de él.",
    "[P40]",
    "—No lo sé,",
    "Jonathan admitió, su voz sonando extrañamente calmada.",
    "—Pero no me siento en peligro. Me siento... en casa.",
    "La criatura sonrió, una expresión imposible en un rostro sin carne, pero que transmitía calidez genuina.",
    "—Porque lo estáis, hermanos. Este mundo nunca fue vuestro verdadero hogar. Sois fragmentos de algo mucho más grande, dispersados a través del tiempo para proteger lo que amáis.",
    "Extendió una mano hecha de hueso pulido hacia Jonathan.",
    "—Tocad mi mano, y recordaréis quiénes fuisteis antes de ser humanos —vuestras vidas como seres de otras civilizaciones—. Recordaréis el amor que os movió a fragmentaros.",
    "Miguel levantó su arma, apuntando directamente a la criatura.",
    "—¡Aléjate de él!",
    "Pero la criatura no se movió, no mostró miedo.",
    "En su lugar, giró hacia Miguel con expresión de profunda tristeza.",
    "—Miguel Santos, hijo de María, nieto de Carlos. Tu bisabuelo vio una de nuestras manifestaciones en 1943, durante la guerra. Escribió sobre ello en su diario, páginas que tu familia guardó pero nunca entendió.",
    "Miguel sintió que su mundo se tambaleaba. Las piernas le temblaron y tuvo que apoyarse contra la fortificación para no caer.",
    "—¿Cómo puedes saber eso?",
    "[HTML]<p class=\"dialogue major-revelation\">—Porque llevamos registros de cada uno de vosotros. Cada nacimiento, cada muerte, cada generación que nos acerca más al momento en que podríais elegir recordar.</p>",
    "[P41]",
    "En el Centro de Comando —búnker de hormigón armado cinco pisos bajo tierra con paredes de acero reforzado—, el General Thomas Kim observaba múltiples pantallas de alta definición que mostraban situaciones similares desarrollándose en todo el perímetro. Soldados bajando sus armas, civiles caminando voluntariamente hacia las zonas de actividad, familias enteras abandonando sus hogares para dirigirse al valle.",
    "Y todos ellos tenían una cosa en común: estaban en la lista de los 2,847.",
    "—General, los números no mienten,",
    "Trevor Williams reportó, estudiando los datos que llegaban desde múltiples agencias de inteligencia en su tableta militar rugosa.",
    "—Cada persona que está respondiendo al llamado tiene el mismo marcador genético —una secuencia específica de ADN que actúa como una especie de código de identificación ancestral—. ADN con secuencias que nuestros científicos han estado clasificando como 'basura' durante décadas —partes del código genético humano que no parecen tener función conocida—.",
    "—¿Y la Dra. Yun?",
    "—En camino. Pero General, hay algo más. Su bebé... los escáneres médicos muestran que el feto tiene una concentración de estas secuencias anómalas cinco veces mayor que la madre.",
    "[HTML]<p>Thomas sintió un escalofrío. <span class=\"dialogue\">—¿Qué está sugiriendo?</span></p>",
    "—Que cada generación está evolucionando, preparándose. Y que esta generación, los bebés que nacen ahora, podrían ser diferentes a cualquier cosa que hayamos visto antes.",
    "[HOOK]Como si hubiera escuchado sus palabras, todas las pantallas del centro de comando parpadearon simultáneamente. Cuando se estabilizaron, mostraban la misma imagen: la estructura de hueso en el valle había crecido exponencialmente, convirtiéndose en algo que parecía una catedral gótica diseñada por una mente que no conocía las limitaciones de la física —arcos que se sostenían sin soporte, torres que desafían la gravedad—.",
    "[P42]",
    "Sophie llegó al centro de comando escoltada por dos soldados que la miraban con una mezcla de respeto y nerviosismo. Su embarazo avanzado hacía que cada paso fuera una prueba, pero no era el peso del bebé lo que la agotaba. Era la energía que pulsaba constantemente a través de su sangre, como si cada célula de su cuerpo estuviera despertando a un propósito que había dormido durante milenios —una función biológica programada hace eones—.",
    "[HTML]<p><span class=\"dialogue\">—Doctora, gracias por venir,</span> General Kim se acercó, pero se detuvo a varios pasos de distancia. <span class=\"dialogue\">—¿Cómo se siente?</span></p>",
    "[HTML]<p><span class=\"dialogue\">—Como si estuviera recordando un sueño que nunca tuve,</span> admitió Sophie, colocando una mano sobre su vientre. <span class=\"dialogue\">—Y mi bebé... se mueve constantemente, como si estuviera tratando de decirme algo.</span></p>",
    "[HTML]<p>Trevor se acercó, mostrándole una tableta con datos genéticos. <span class=\"dialogue\">—Dra. Yun, ¿puede explicar esto?</span></p>",
    "Sophie estudió los datos, y gradualmente su expresión cambió de confusión a asombro, y luego a algo que se acercaba al terror.",
    "—Esto desafía todo lo que sabemos sobre evolución. Estas secuencias... no evolucionaron naturalmente. Son demasiado complejas, demasiado organizadas —como código de computadora biológico—. Parecen haber sido... diseñadas. E insertadas en líneas genéticas específicas.",
    "—Pero están en su ADN. Y en el de 2,846 personas más.",
    "—Espere,",
    "Sophie estudió los patrones más cuidadosamente, su entrenamiento científico luchando contra una intuición creciente.",
    "[HTML]<p class=\"dialogue major-revelation\">—Estas secuencias no son aleatorias. Forman patrones específicos, como... como si cada una de nosotras fuera una pieza de un rompecabezas más grande —un plan elaborado durante millones de años—. Llevamos fragmentos de información genética diseñada para activarse bajo ciertas condiciones específicas —como un programa durmiente esperando la señal correcta, como software instalado pero no ejecutado—.</p>",
    "[P43]",
    "El silencio que siguió a sus palabras fue interrumpido por una alarma que comenzó a sonar por todo el centro de comando. En las pantallas principales, las imágenes del valle mostraban algo que desafiaba toda lógica militar.",
    "Las criaturas no estaban atacando. Estaban construyendo.",
    "Cientos de entidades esqueléticas trabajaban en perfecta coordinación, usando materiales que parecían manifestarse de la nada para expandir la estructura ósea. Pero no era construcción en el sentido tradicional —usando herramientas y materiales conocidos—. Era crecimiento orgánico, como si estuvieran cultivando una ciudad viviente hecha de hueso y luz —estructuras que crecen como plantas pero mantienen formas arquitectónicas complejas—.",
    "[HTML]<p><span class=\"dialogue\">—¿Qué están haciendo?</span> murmuró Thomas.</p>",
    "Sophie se acercó a las pantallas, y mientras observaba, su bebé se movió violentamente en su vientre. Por un momento, sintió como si pudiera ver a través de otros ojos, entender con una mente que era suya pero que también era infinitamente más antigua.",
    "[HTML]<p class=\"dialogue major-revelation\">—Están preparando un lugar para nosotros. Un lugar donde podamos elegir.</p>",
    "—¿Elegir qué?",
    "—Entre seguir siendo humanos y morir cuando lleguen los devoradores... o recordar lo que fuimos antes y tener el poder de proteger este mundo.",
    "En la pantalla, la estructura pulsaba con una luz que era simultáneamente hermosa y aterradora. Y desde su interior, una voz comenzó a cantar, una melodía que llegaba no a través de ondas sonoras sino directamente a la parte más profunda de la consciencia.",
    "[HTML]<p class=\"hook cliffhanger\">Era una canción de bienvenida. Y 2,847 personas alrededor del mundo la estaban escuchando.</p>",
    "[P44]",
    "En el Puesto Avanzado Delta, Jonathan finalmente extendió su mano hacia la criatura de marfil. El momento en que sus dedos se tocaron, su mundo cambió para siempre.",
    "[HTML]<p class=\"transformation-sequence\">No fue dolor lo que sintió, sino un reconocimiento tan profundo que le quitó el aliento —como recordar repentinamente un sueño olvidado que resulta ser completamente real—. Memorias que no eran suyas pero que eran absolutamente reales inundaron su mente: civilizaciones que se alzaban entre las estrellas —imperios que abarcaban sistemas solares completos—, guerras libradas a través de dimensiones —batallas que se extendian por realidades paralelas—, un amor tan puro que había motivado el sacrificio más grande que el universo había conocido.</p>",
    "Vio a Eloria como había sido antes de la fragmentación, una consciencia cósmica que había elegido dispersarse por amor a criaturas que ni siquiera habían evolucionado todavía. Vio los veinticuatro reinos, cada uno perfecto en su propia manera, cada uno eligiendo la muerte voluntaria para dar a la humanidad una oportunidad de sobrevivir.",
    "Y se vio a sí mismo, no como Jonathan Morales, soldado mexicano de veintiocho años, sino como un fragmento de algo mucho más grande: un general de los Cantantes de Huesos —una civilización que usaba frecuencias sonoras como tecnología—, que había comandado flotas que navegaban entre estrellas usando música como combustible.",
    "[HTML]<p><span class=\"dialogue latin-inscription\">—Recordas,</span> susurró la criatura, y su voz ahora sonaba familiar, querida. <span class=\"dialogue\">—Mi hermano, mi general, recordas.</span></p>",
    "Miguel observó cómo Jonathan cerró los ojos un instante, la mandíbula tensa, la mano de la criatura aún sostenida entre las suyas. Cuando los abrió, algo había cambiado en ellos para siempre. Un exilio de 230 millones de años había terminado.",
    "[HTML]<p><span class=\"dialogue transformation-complete\">—Sí,</span> susurró Jonathan, su voz cambiando, adquiriendo armónicos que no deberían haber sido posibles con cuerdas vocales humanas —frecuencias múltiples superpuestas en una sola voz—. <span class=\"dialogue\">—Recuerdo. Recuerdo todo.</span></p>",
    "[HTML]<div class=\"intercapitulo\"><h4>INTERCAPÍTULO 5</h4><h5>REGISTRO MÉDICO - HOSPITAL YONSEI</h5><div class=\"document-header\"><p><strong>PACIENTE:</strong> Yun, Sophie (ID: 847-2847-001)</p><p><strong>CONDICIÓN:</strong> Embarazo de 36 semanas</p><p><strong>MÉDICO TRATANTE:</strong> Dr. Kim Jae-sung</p><p><strong>FECHA:</strong> [ACTUAL]</p></div><div class=\"document-content\"><p><strong>OBSERVACIONES ANÓMALAS:</strong></p><p>La paciente presenta cambios fisiológicos sin precedentes durante el tercer trimestre. Análisis sanguíneos revelan:</p><ul><li>Hemoglobina con estructura molecular modificada</li><li>Actividad mitocondrial 300% por encima de niveles normales —las \"centrales eléctricas\" de las células trabajando a velocidad sobrehumana—</li><li>Presencia de proteínas no catalogadas en medicina humana</li></ul><p><strong>ESTADO FETAL:</strong> El feto muestra desarrollo acelerado pero estable. Escáneres cerebrales indican patrones de actividad neuronal complejos —ondas cerebrales que normalmente solo se ven en adultos altamente entrenados—, sugerentes de consciencia prenatal avanzada.</p><p><strong>NOTA ESPECIAL:</strong> Durante el último ultrasonido, el feto pareció responder a estímulos externos que la madre no podía percibir. En un momento, dirigió su rostro hacia la pantalla como si pudiera ver a través del útero.</p><p><strong>RECOMENDACIÓN:</strong> Monitoreo constante. Esta paciente representa un caso único en la literatura médica.</p><p class=\"medical-note\"><em>NOTA PERSONAL: He entregado copias de este expediente a las autoridades militares según sus instrucciones. Que Dios nos ayude si no somos los únicos.</em></p></div></div>",
  ]
};
