const CAPITULO = {
  numero: 2,
  titulo: "Despertar Sísmico",
  paginas: "13-20 - Cronología de Máximo Suspenso",
  nav: {
    anterior: { href: "capitulo_01_nuevo.html", label: "← Capítulo 1" },
    siguiente: { href: "capitulo_03.html", label: "Capítulo 3 →" }
  },
  contenido: [
    "[P13]",
    "[HR]",
    "[HTML]<h4 class=\"dev-subtitle\">🌍 DESPERTAR SÍSMICO</h4>",
    "[HTML]<p><strong>Instituto Sismológico Nacional de Corea - Madrugada</strong></p>",
    "El Dr. Park Sung-min no había dormido en cuarenta y ocho horas.",
    "Los datos lo obsesionaban. Los terremotos seguían un patrón imposible. Mismo intervalo. Misma profundidad exacta. Círculos concéntricos perfectos alrededor del Valle Cheongmyeong.",
    "\"La naturaleza no funciona con relojes suizos,\" murmuró, frotándose los ojos irritados.",
    "Algo sistemático despertaba bajo la tierra.",
    "Hace seis meses, después del primer evento en Amsterdam, el gobierno coreano había establecido protocolo: cualquier anomalía sísmica con periodicidad artificial debía reportarse inmediatamente a línea militar directa. Park tenía el número memorizado desde la primera reunión de seguridad nacional.",
    "Marcó con dedos temblorosos por cafeína y agotamiento. \"Protocolo Marzo activado. Valle Cheongmyeong. Periodicidad artificial confirmada. Profundidad constante. Requiere intervención inmediata.\"",
    "[HR]",
    "[HTML]<h4 class=\"dev-subtitle\">👮 HENRY ASIGNADO AL CASO MAYA</h4>",
    "[HTML]<p><strong>Estación de Policía Metropolitana de Seúl - Esa misma mañana</strong></p>",
    "El Oficial Henry Lee ajustaba la radio por quinta vez. Sus manos sudaban dentro de los guantes reglamentarios.",
    "Cinco días de servicio. Su compañero asignado, el veterano Oficial Kim Tae-sung, había llamado enfermo esta mañana—fiebre súbita, sangrado nasal. Henry estaba solo cuando la llamada de desaparición entró. Protocolo decía esperar refuerzos. Pero los refuerzos estaban a 2 horas por las montañas.",
    "\"Henry.\" El Sargento Choi cerró la puerta de su oficina. Veterano con décadas de servicio, raramente se veía así de tenso. \"Tenemos una desaparición en el Valle Cheongmyeong. Maya Park, youtuber que investigaba la muerte de su hermano.\"",
    "\"¿Desaparición confirmada?\"",
    "\"Hace casi una semana. Su editor acaba de publicar su último video. Se está volviendo viral y los hospitales están recibiendo... casos relacionados.\"",
    "Henry tragó saliva. \"¿Qué grabó?\"",
    "\"Símbolos. Patrones que su hermano dibujó antes de morir.\" Choi giró su monitor. \"Pero mira los comentarios.\"",
    "Miles de comentarios. Gente reportando pesadillas idénticas. Dolores inexplicables. Familias llevando hijos a emergencias con fiebres súbitas y sangrados nasales.",
    "\"Los hospitales están colapsando con casos relacionados al video. Pánico masivo.\"",
    "Un escalofrío primitivo recorrió la columna vertebral de Henry. No era miedo profesional.",
    "\"¿Contacto cada veinte minutos?\" Su voz sonó más aguda de lo que pretendía.",
    "\"Cada diez,\" corrigió Choi.",
    "[HR]",
    "[HTML]<h4 class=\"dev-subtitle\">👁️ PRIMERA VISUALIZACIÓN MILITAR</h4>",
    "[HTML]<p><strong>Centro de Comando Conjunto - Simultáneo</strong></p>",
    "\"General Kim.\" Mayor Sarah Chen, veterana que raramente perdía la compostura. \"Confirmación visual de algo... que no entiendo.\"",
    "Dron de reconocimiento mostrando movimiento entre las sombras del valle.",
    "\"Congele imagen. Aumente sector 7-B.\"",
    "Imagen pixelada clarificándose. Sarah ahogó un grito.",
    "Esqueleto. Vivo. Arrastrándose en cuatro extremidades, columna grotescamente alargada, vértebras como púas. Movimientos fluidos, líquidos. Huesos que habían olvidado limitaciones anatómicas.",
    "\"Enorme. El algoritmo detecta doce figuras similares en el perímetro.\"",
    "El General Kim había visto de todo en su carrera. Pero nada lo preparó para esto.",
    "\"Los terremotos comenzaron hace 24 días.\"",
    "\"Jung-ho Park visitó el valle hace casi un mes. Estudiante de matemáticas, genio. Estuvo horas documentando los símbolos, calculando patrones. Tres días después de regresar: colapso cardíaco súbito. Los terremotos comenzaron poco después de su muerte.\"",
    "\"¿Coincidencia?\"",
    "\"Imposible. Su muerte activó algo. La autopsia mostró anomalías óseas severas, calcificación en las válvulas del corazón. Como si su cuerpo hubiera... cambiado.\"",
    "\"Su hermana Maya investigaba misterios online. Desapareció la semana pasada buscando respuestas. Su editor encontró el último video que grabó y lo publicó esta madrugada. Ya es viral.\"",
    "[HR]",
    "[HTML]<h4 class=\"dev-subtitle\">💀 HENRY ENCUENTRA PATRONES ÓSEOS</h4>",
    "[HTML]<p><strong>Valle Cheongmyeong - Media mañana</strong></p>",
    "La ausencia total de sonido golpeó a Henry. Concreta. Irrefutable.",
    "El valle había perdido todos los sonidos naturales. Ni insectos ni viento. Solo el eco de sus propios latidos rebotando contra las montañas.",
    "Apagó el motor. Sus pasos sobre la grava sonaron secos, aislados en el silencio.",
    "Los huesos estaban organizados.",
    "Espirales logarítmicas de fémures. Fractales de costillas y vértebras. Patrones que lastimaban los ojos solo de mirarlos.",
    "Demasiados huesos. Miles. Como si hubieran desenterrado un cementerio entero y lo reorganizaron. Demasiados para ser solo personas.",
    "\"Control, Unidad 23.\" Su voz tembló. \"Escena anómala. Patrones óseos complejos. Necesito—\"",
    "Crujido seco entre los arbustos.",
    "Henry giró, mano instintiva hacia la pistola.",
    "A veinte metros, algo imposible se movía. Su cerebro se negó a procesar la información.",
    "Esqueleto en cuatro extremidades. Columna ondulante como serpiente ósea. Vértebras independientes produciendo sonidos secos mientras se movía con fluidez antinatural.",
    "El Osamental Rastrero se detuvo.",
    "Cráneo girando 180 grados para \"mirarlo\" directamente.",
    "Henry olvidó cómo respirar.",
    "Parálisis total. Su mente se bloqueó. El cuerpo se negaba a responder.",
    "Las manos le temblaron sin control.",
    "El Osamental permaneció inmóvil. Luego se deslizó hacia atrás con movimiento fluido y desapareció entre la vegetación marchita.",
    "\"Control...\" Voz ronca, garganta casi cerrada. \"Necesito refuerzos inmediatos.\"",
    "\"¿Unidad 23? Situación.\"",
    "Cómo explicar un esqueleto vivo sin que lo declararan mentalmente incompetente.",
    "\"Posible sospechoso. Solicito especialistas.\"",
    "Encontró la cámara de Maya volcada entre la hierba seca. Cámara profesional con el logo del canal impreso.",
    "Carcasa agrietada. Lente rota. Completamente apagada.",
    "Henry conectó una batería de repuesto de su kit. La cámara encendió. Última grabación en la tarjeta de memoria: veintitrés minutos.",
    "[HR]",
    "[HTML]<h3>PÁGINA 14</h3>",
    "[HTML]<h4 class=\"dev-subtitle\">🎥 VIDEO DE MAYA - LA VERDAD DE JUNG-HO (Grabado hace 6 días - Atardecer)</h4>",
    "La pantalla mostró a Maya Park. Joven, ojos rojos pero con determinación.",
    "\"Valle Cheongmyeong. Si están viendo esto, algo me pasó. Mi hermano Jung-ho murió hace 3 semanas. Solo tenía quince años. Era un genio, matemáticas. Colapso cardíaco sin explicación.\"",
    "Cámara enfocando piedras cubiertas de musgo con símbolos grabados profundamente en la roca.",
    "\"Jung-ho dibujó estos símbolos obsesivamente antes de morir. Idénticos. Encontré su cuaderno: ecuaciones, patrones fractales, coordenadas que llevaban aquí.\"",
    "Acercó la cámara a los símbolos sin tocarlos. Zoom digital.",
    "\"No sé qué significan. Pero están en roca volcánica de millones de años. No son recientes.\"",
    "Voz quebrándose. \"Jung-ho escribió algo en su cuaderno: 'Los símbolos contienen secuencias matemáticas. Si aplico teoría de números primos y patrones fractales, obtengo constante: 2,847. No sé qué significa este número. ¿Coordenadas? ¿Profundidad? ¿Cantidad de algo? Si los símbolos reaccionan cuando los toco, sabré si soy parte del patrón.'\"",
    "Respiración acelerada. \"Voy a tocarlos. Si pasa algo... si no regreso... alguien debe saber que Jung-ho tenía razón.\"",
    "Sus dedos se acercaron a la piedra—",
    "Sonido. Vibraciones visibles en el aire. La cámara captó distorsión ondulante.",
    "Maya jadeó. Retiró la mano rápidamente. \"Se sienten calientes. Como—\"",
    "Crujido seco fuera de cámara.",
    "\"¿Qué—?\"",
    "Cámara girando violentamente. Entre los árboles, movimiento imposible.",
    "\"No. No no no.\" Pánico puro quebrando su voz entrenada. \"Esqueleto. Caminando. Tres metros de alto.\"",
    "Carrera desesperada. Sollozos. Cámara golpeando su cuerpo.",
    "Corte abrupto.",
    "[HR]",
    "[HTML]<h3>PÁGINA 15</h3>",
    "[HTML]<h4 class=\"dev-subtitle\">📊 ANÁLISIS GLOBAL DEL FENÓMENO</h4>",
    "[HTML]<p><strong>Centro de Comando - Mientras Henry ve el video</strong></p>",
    "\"General, situación crítica.\" Sarah Chen proyectó datos médicos. \"El video de Maya se está volviendo viral desde esta madrugada. Pero los cientos de casos que tenemos no comenzaron hoy.\"",
    "\"Estos pacientes empezaron a llegar hace tres semanas, cuando Jung-ho murió. Dispersos globalmente. Ningún hospital tiene más de cuarenta casos. Por eso nadie conectó los puntos hasta ahora.\"",
    "\"¿Por qué no se conectaron los puntos antes?\"",
    "\"Porque no había conexión visible. Pacientes de diferentes países, sin contacto entre ellos, sin viajes comunes. Solo hoy, cuando vimos los marcadores genéticos idénticos, comprendimos: no es brote. Es activación simultánea de personas que ya nacieron con esto.\"",
    "Pantalla mostrando reportes médicos clasificados con fechas:",
    "[HTML]<p><strong>Progresión documentada:</strong></p>",
    "Primeros días: Dolor óseo severo, fiebres altas sin causa infecciosa, sangrados nasales.",
    "Primera semana: Hospitalizados. Radiografías muestran densidad ósea alterada en patrones simétricos. Calcio elevado en sangre.",
    "Semanas siguientes: Fracturas geométricas visibles en tomografías. Dolor que no responde a medicamentos. Tres muertes por fallo orgánico.",
    "\"Lo crítico: estos 847 casos comparten marcadores genéticos idénticos. ADN con secuencias que no coinciden con ninguna base de datos humana.\"",
    "Kim procesó la información. \"¿Ya nacieron con esto?\"",
    "\"Exacto. El video de Maya no los infectó. Confirmó el patrón. Ahora sabemos qué estamos buscando: descendientes.\"",
    "Kim observó la transmisión del dron. \"Las criaturas se están multiplicando. Están formando el patrón exacto de los terremotos.\"",
    "\"Movilicen equipo de contención especial. Contacten al Dr. Trevor Williams de la DEA.\"",
    "[HR]",
    "[HTML]<h4 class=\"dev-subtitle\">🧪 TREVOR ANALIZA POLVO DE HUESO</h4>",
    "[HTML]<p><strong>Laboratorio Temporal DEA, Instalación Militar Osan - Simultáneo</strong></p>",
    "Dr. Trevor Williams llevaba seis meses rastreando \"polvo de hueso\" en cinco continentes. Cientos de casos, la mayoría en Los Ángeles. Cuando detectó concentración de casos en Corea hace dos semanas, voló inmediatamente. La base militar le proporcionó laboratorio temporal.",
    "Los usuarios reportaban cosas imposibles. Memorias que no eran suyas. Idiomas que nunca habían aprendido.",
    "No era adicción. Era algo más.",
    "Hace dos semanas, sus análisis revelaron el patrón: el polvo solo afectaba a personas con marcadores genéticos específicos. No todos. Solo descendientes de linajes raros.",
    "\"No es droga,\" había dictado a su grabadora. \"Es test de identificación genética. Alguien está catalogando descendientes.\"",
    "Teléfono satelital interrumpió sus pensamientos. \"Dr. Williams, Centro de Comando. Helicóptero en ruta. Llega en minutos. Situación crítica en Valle Cheongmyeong.\"",
    "Trevor miró el contenedor de titanio con sus últimas muestras. Bajo el microscopio, las partículas vibraban con un ritmo constante.",
    "No era vida. Era resonancia física. Como cristales respondiendo a una frecuencia específica.",
    "[HR]",
    "[HTML]<h4 class=\"dev-subtitle\">🎵 LA MÚSICA COMIENZA</h4>",
    "[HTML]<p><strong>Valle Cheongmyeong - Poco después</strong></p>",
    "Henry había contado doce de esas cosas en la última media hora. Se movían con propósito, como patrullando. La radio reportó que los drones detectaban docenas formando un círculo gigante. Él solo veía una parte.",
    "No lo atacaban. Solo observaban.",
    "Un pensamiento horrible: en el video de Maya, esas cosas la perseguían. Ahora permanecían quietas. ¿Y si la dejaron correr solo lo suficiente para que la cámara quedara donde alguien pudiera encontrarla?",
    "Sonido nuevo. No crujidos secos. Música.",
    "Distante pero clara. Melodía desconocida que, inexplicablemente, sentía familiar. Como canción de infancia medio olvidada.",
    "\"Control, ¿escuchan esto?\" Alzó la radio hacia la fuente del sonido.",
    "Estática. La música interferiría las señales.",
    "Henry comprendió con escalofrío: Jung-ho había activado algo. Maya desapareció buscando respuestas.",
    "Y la música venía de las profundidades. De donde venían los terremotos.",
    "[HR]",
    "[HTML]<h3>PÁGINA 16</h3>",
    "[HTML]<h4 class=\"dev-subtitle\">🚁 LLEGADA DE FUERZAS ESPECIALES</h4>",
    "Motores diesel rompiendo el silencio antinatural.",
    "Convoy de SUV blindadas negras. Placas militares. Fuerzas especiales: cuando las situaciones salen de todos los protocolos normales.",
    "Capitán Morrison, traje táctico sin insignias. Porte inconfundible de veterano. \"Oficial Lee. Entregue toda la evidencia.\"",
    "\"Entidades hostiles en perímetro.\"",
    "Morrison no pareció sorprendido. \"Osamentales Rastreros. Así las llamamos.\"",
    "Henry procesó lentamente. \"¿Las... conocían?\"",
    "\"Esto no es nuevo.\" Morrison pausó. \"Hemos visto... cosas similares en otros sitios arqueológicos. Desde marzo. Apariciones breves. Siempre lo mismo: alguien toca algo antiguo, muere en días, aparecen criaturas y luego desaparecen.\"",
    "\"¿Y aquí?\"",
    "\"Aquí es diferente.\" Morrison señaló el valle. \"No desaparecen. Se multiplican. Jung-ho despertó el epicentro real.\"",
    "Señaló el centro del valle. Osamentales moviéndose en sincronía, formando un círculo gigante y perfecto.",
    "\"No sabíamos qué conectaba los eventos. Hasta que identificamos el patrón: polvo de hueso, marcadores genéticos. Descendientes de algo antiguo. El video de Maya lo aceleró todo. Ahora saben que existen.\"",
    "Música intensificándose, más compleja. No del horizonte. De abajo. De las profundidades exactas donde ocurrían los terremotos.",
    "[HR]",
    "[HTML]<h4 class=\"dev-subtitle\">📊 TREVOR LLEGA AL CENTRO DE COMANDO</h4>",
    "[HTML]<p><strong>Centro de Comando - Poco después</strong></p>",
    "Trevor Williams descendiendo del helicóptero mientras pantallas mostraban imposibilidad.",
    "\"Doctor, necesitamos análisis.\" Kim sin preámbulos.",
    "Osamentales formando círculo perfecto de 2,847 metros. Centro del suelo agrietándose.",
    "\"El polvo no es droga. Es identificador.\" Trevor proyectó sus análisis. \"Vibra a cierta frecuencia. Solo ciertos huesos responden. Como un diapasón. Cuando resuenan, causan los síntomas. Dolor, calcificación.\"",
    "Sarah Chen: \"Cientos de casos hospitalizados con síntomas reales. Todos comparten el mismo ADN alterado.\"",
    "\"Millones vieron el video. Miles reportan síntomas por pánico. Pero solo los que tienen el ADN correcto están realmente afectados. Los descendientes.\"",
    "[HTML]<div class=\"intercapter-break\"><h2>DOCUMENTO FORENSE CLASIFICADO</h2><h4 class=\"dev-subtitle\">📋 ADN NO-TERRESTRE CONFIRMADO</h4><div class=\"document\"><div class=\"document-header\"><p><strong>CLASIFICADO - NIVEL 5</strong><br><strong>HOSPITAL UNIVERSITARIO SEÚL</strong><br><strong>FORENSE</strong></p></div><div class=\"document-content\"><p><strong>Dr. Jason Lee - Médico Forense Jefe</strong></p><p><strong>Valle Cheongmyeong - Muestras Óseas</strong></p><p><strong>COMPOSICIÓN ANÓMALA:</strong></p><ul><li>Densidad ósea varias veces superior a humano normal - resistencia similar al metal</li><li>Elementos desconocidos - isótopos que no deberían existir</li><li>Estructura cristalina fractal - patrones matemáticamente imposibles</li></ul><p><strong>ADN IMPOSIBLE:</strong></p><ul><li>Secuencias pre-terrestres - millones de años anteriores a vida conocida</li><li>Código tricatenario - tres cadenas ADN vs. dos estándar terrestres</li><li>Información genética de especies nunca existentes en este planeta</li></ul><p class=\"document-warning\"><strong>CONCLUSIÓN:</strong> ADN NO-TERRESTRE</p><p class=\"document-conclusion\">Elevar a seguridad nacional inmediata.</p></div></div></div>",
    "Técnico gritando: \"Sismo 4.2. Epicentro Valle Cheongmyeong. Profundidad—\"",
    "\"2,847 metros,\" interrumpió Trevor.",
    "\"Exacto.\"",
    "Dron de reconocimiento mostrando algo emergiendo del centro del círculo. No esqueleto rastrero. Estructura orgánica.",
    "Huesos fusionándose en tiempo real. Torre retorcida de vértebras y costillas entrelazadas creciendo cada minuto.",
    "\"No construye,\" corrigió Trevor. \"Crece como organismo vivo. Cada descendiente es una célula potencial del organismo completo.\"",
    "[HR]",
    "[HTML]<h3>PÁGINA 17</h3>",
    "[HTML]<h4 class=\"dev-subtitle\">🏗️ CONSTRUCCIÓN DEL TRONO</h4>",
    "[HTML]<p><strong>Valle Cheongmyeong - Mediodía</strong></p>",
    "Torre de huesos creciendo frente a los ojos de Henry. Ya superaba los techos de las casas y seguía. Osamentales Rastreros moviéndose en círculos precisos alrededor de la estructura central.",
    "La fuente: no desenterraban huesos. Los Osamentales depositaban fragmentos óseos de sus propios cuerpos. Vértebras desprendiéndose, regenerándose instantáneamente. Ciclo continuo de creación y donación.",
    "\"Se están desmembrando y regenerando. Usan sus propios cuerpos como material de construcción.\"",
    "Morrison observó con prismáticos. \"Conversión de calcio ambiental en materia ósea. Cada Osamental es fábrica viviente.\"",
    "\"Convierten calcio del suelo, del aire. Los terremotos extraen minerales desde las profundidades.\"",
    "Radio crepitando: \"YouTube eliminó el video después de millones de vistas. Demasiado tarde. Ya hay copias por todas partes. TikTok, Twitter, Instagram. El total superó los seis millones. Descontrolado.\"",
    "Henry sintió vibración profunda originándose en su esqueleto. No dolor físico real. Sensación de resonancia, como estar parado frente a altavoces gigantes que vibran huesos sin dañarlos.",
    "Ahora, a 50 metros del epicentro, la vibración era ensordecedora dentro de su cráneo.",
    "\"Siento algo. Como si mis huesos vibraran.\" Su voz tembló.",
    "Morrison revisó su tablet. \"Henry Lee. Tu madre es Park Min-seo, ¿verdad?\" Pausó. \"El apellido Park está por todas partes en los casos. Docenas. No es coincidencia.\"",
    "\"No son síntomas médicos todavía. Es resonancia directa. Estar tan cerca del epicentro hace que tus huesos detecten la fuente. Los hospitalizados tuvieron contacto con el polvo o exposición prolongada. Lo tuyo es solo vibración por ahora.\"",
    "\"¿Cuánto tiempo tengo antes de que se vuelva físico?\"",
    "\"Desconocido. Pero mientras no toques nada contaminado con polvo de hueso, deberías estar relativamente seguro.\"",
    "\"Resonancia ósea acelerada por distancia. Mis huesos quieren moverse hacia la torre. Me llaman.\"",
    "Morrison guardó silencio un momento. \"Notas de Jung-ho mencionaban un 'pacto olvidado hace 230 millones de años'. No dejó explicación clara. Solo ecuaciones.\"",
    "Torre alcanzando veinte metros, dominando el valle.",
    "En la cima, estructura compleja formándose. Trono hecho de huesos entrelazados en patrones imposiblemente complejos.",
    "Henry tuvo certeza terrible: alguien vendría a reclamarlo. La Reina que Jung-ho despertó accidentalmente.",
    "Música resonando directamente en cada hueso. Su esqueleto como instrumento siendo tocado.",
    "Comprendió: no ruido aleatorio. Palabras. Invitación. Bienvenida.",
    "Llamado de regreso a casa.",
    "Maya Park había sido la primera en responder a la convocatoria de la Reina de los Osamentales."
  ]
};
