const CAPITULO = {
  numero: "12",
  titulo: "La Última Transmisión",
  paginas: "93-100",
  nav: {
    anterior: { href: "capitulo_11_5.html", label: "← Capítulo 11.5" },
    siguiente: { href: "capitulo_13.html", label: "Capítulo 13 →" }
  },
  contenido: [
    "[P93]",
    "[LOC]Centro de Transmisión Improvisado, Ciudad Ósea - 18:45 hrs - Día 21",
    "[OPEN]Maya Park sabía que esta sería la transmisión más importante de su vida, y posiblemente la última historia que tendría la oportunidad de contar.",
    "Veintiún días habían pasado desde su primera transformación. Veintiún días sirviendo como puente entre dos especies mientras observaba a la humanidad desgarrarse.",
    "La muerte de Trevor Williams tres días atrás había desencadenado protestas globales, bombardeos de estructuras óseas, escalada de violencia que amenazaba convertir la primera guerra entre especies en extinción mutua.",
    "—Configuración de emergencia para MinJung Oscura, transmisión final, murmuró Maya ajustando el equipo híbrido que los Tejedores de Carne construyeron para ella.",
    "Combinación de tecnología humana y biotecnología alienígena que amplificaba exponencialmente su alcance normal.",
    "—Hola a todos. Mi nombre es Maya Park, y durante los últimos tres años han seguido mi canal MinJung Oscura mientras investigaba misterios que resulta que no eran tan misteriosos después de todo.",
    "Su imagen se transmitía a más de 50 millones de pantallas —cifra imposible para su canal normal—.",
    "La tecnología híbrida hackeaba automáticamente redes de transmisión, sistemas de emergencia y plataformas digitales para empujar su señal.",
    "[P94]",
    "—Lo que voy a decirles va a sonar a ciencia ficción. Pero tengo 47 minutos de transmisión garantizada antes de que las fuerzas gubernamentales lleguen a esta ubicación, y 47 minutos para explicar la elección más importante que nuestra especie jamás ha enfrentado.",
    "Maya había pasado días preparando esta presentación. No solo como YouTuber, sino como alguien que había vivido en ambos lados de la transformación: había sido completamente humana, luego completamente transformada, y ahora existía en un estado intermedio que le permitía entender ambas perspectivas.",
    "—Hace 230 millones de años, mucho antes de los dinosaurios, este planeta fue habitado por 24 civilizaciones que alcanzaron niveles de desarrollo que nosotros apenas podemos imaginar. No se extinguieron. Eligieron fragmentarse, dispersar sus consciencias en el código genético de formas de vida futuras, esperando que algún día esas especies evolucionaran lo suficiente como para reunirse con ellos.",
    "Mientras hablaba, Maya mostró imágenes que había grabado durante sus semanas en la Ciudad Ósea: los archivos vivientes que contenían la historia completa de la Tierra, visualizaciones de las civilizaciones ancestrales, documentación de los 2,847 descendientes y sus ubicaciones alrededor del mundo.",
    "—Somos esas especies futuras. Algunos de nosotros, al menos. Y ahora tenemos que elegir si queremos evolucionar con ellos o continuar siendo humanos. Pero hay algo más que los gobiernos no les han dicho: si no hacemos esta elección pronto, algo viene del espacio que va a hacer que la elección sea irrelevante.",
    "[P95]",
    "En el centro de comando militar a 200 kilómetros de distancia, el General Thomas Kim observaba la transmisión de Maya con una mezcla de respeto y terror. Sus asesores le gritaban que cortara la señal, que enviara fuerzas para detenerla, que clasificara la información que estaba revelando.",
    "—No, dijo simplemente. —La gente tiene derecho a escuchar esto.",
    "—General, está revelando información clasificada de máximo nivel. Los protocolos requieren...",
    "—Los protocolos fueron escritos por personas que nunca imaginaron esta situación. Maya está haciendo lo que Trevor Williams murió tratando de hacer: darle a la humanidad la información que necesita para elegir su propio destino.",
    "Mientras tanto, Maya continuaba su transmisión, ahora mostrando imágenes que habían sido capturadas por telescopios espaciales pero mantenidas clasificadas: objetos masivos aproximándose al sistema solar a velocidades imposibles.",
    "—Los devoradores llegarán en aproximadamente tres semanas. Son entidades cósmicas que consumen civilizaciones completas. No son malvados; simplemente hambrientos. Y la única defensa que ha funcionado contra ellos es convertirlos en algo que ya no quiere destruir.",
    "[P96]",
    "La transmisión de Maya había sido vista por más personas simultáneamente que cualquier evento en la historia humana. En todo el mundo, las reacciones eran intensas y divididas: algunos la llamaban la mensajera de la verdad, otros la consideraban una traidora a la especie humana.",
    "Pero Maya no había terminado.",
    "—Sé que algunos de ustedes están pensando que he sido lavada del cerebro, que ya no soy humana, que no pueden confiar en lo que digo. Así que déjenme contarles mi historia personal.",
    "Maya procedió a narrar su transformación completa: desde su desaparición inicial en el Valle Oscuro hasta su regreso confundido, desde sus primeros contactos con las voces ancestrales hasta su comprensión gradual de lo que realmente estaba pasando. No omitió nada: ni los momentos de terror, ni las pérdidas de humanidad que había experimentado, ni las ocasiones en que había considerado el suicidio antes que continuar cambiando.",
    "—He perdido cosas que consideraba esenciales para ser humana. Ya no sueño de la misma manera. Ya no siento emociones con la misma intensidad. Ya no me relaciono con las personas como antes. Pero también he ganado cosas: puedo ver conexiones que antes eran invisibles, puedo entender conceptos que antes eran imposibles, puedo sentir el dolor y la alegría de otras formas de vida.",
    "—No estoy aquí para decirles qué elegir. Estoy aquí para asegurarme de que entiendan qué están eligiendo.",
    "[P97]",
    "Mientras Maya hablaba, sistemas de alerta comenzaron a sonar en la Ciudad Ósea. Los monitores mostraron formaciones militares convergiendo en su ubicación desde múltiples direcciones: fuerzas especiales de cinco países diferentes, coordinando un ataque conjunto para \"neutralizar la fuente de propaganda alienígena\".",
    "—Veo que mi tiempo se acaba antes de lo esperado. Las fuerzas militares están llegando, y probablemente van a intentar detener esta transmisión.",
    "Maya miró directamente a la cámara con una expresión que combinaba tristeza y determinación.",
    "—Quiero que sepan que, sin importar lo que elijan, los amo. Amo a la humanidad por su imperfección, por su capacidad de crecimiento, por su negativa a aceptar limitaciones. Y amo a las civilizaciones ancestrales por su sabiduría, por su paciencia, por su disposición a esperar 230 millones de años por la posibilidad de reunirse con nosotros.",
    "—Esta transmisión está siendo grabada y almacenada en 847 ubicaciones alrededor del mundo. Sin importar lo que me pase, sin importar lo que les pase a las ciudades óseas, sin importar cuál elección haga la humanidad, alguien en el futuro podrá acceder a esta información y entender qué pasó realmente.",
    "[P98]",
    "Las explosiones comenzaron en el perímetro exterior de la Ciudad Ósea. Maya podía escuchar los disparos, las detonaciones de granadas, los gritos de combate tanto humanos como de las entidades óseas que defendían el lugar.",
    "—Las fuerzas militares han comenzado su asalto. Puedo ver desde aquí que están usando armas tanto convencionales como algunos tipos de munición que parecen diseñadas específicamente para dañar las estructuras óseas.",
    "Maya ajustó la cámara para mostrar las ventanas que revelaban el combate exterior. Soldados humanos avanzaban entre estructuras que se defendían, creando escenas que parecían sacadas de pesadillas: esqueletos gigantescos luchando contra tanques, criaturas de cristal desviando misiles, arquitecturas vivientes reorganizándose para crear cobertura defensiva.",
    "—Esto es lo que la guerra entre especies se ve. No hay buenos o malos aquí, solo dos formas de vida tratando de sobrevivir de maneras que les parecen correctas.",
    "Una explosión particularmente fuerte sacudió el edificio donde Maya estaba transmitiendo. Polvo y fragmentos cayeron del techo, pero ella mantuvo la cámara estable.",
    "—Han logrado penetrar las defensas exteriores. Calculo que tienen aproximadamente diez minutos antes de llegar a esta ubicación.",
    "[P99]",
    "Maya usó esos diez minutos de la manera más eficiente posible: proporcionó coordenadas específicas donde las personas podrían encontrar más información, nombró contactos clave en gobiernos y organizaciones que tenían acceso a datos clasificados, y dio instrucciones detalladas sobre cómo identificar a los descendientes que aún no habían despertado.",
    "—Si conocen a alguien que ha tenido sueños en idiomas que no reconocen, si han visto a personas que parecen saber cosas que nunca aprendieron, si han notado que ciertos individuos no se enferman nunca o sanan más rápido de lo normal, esas personas podrían ser descendientes.",
    "—No los forcen a despertar. No los lleven a las autoridades. Déjenlos elegir cuando estén listos. Pero si eligen transformarse, apóyenlos. Van a necesitar conexiones humanas que los anclen durante el proceso.",
    "Los sonidos de combate se acercaban. Maya podía escuchar botas militares en los corredores exteriores, órdenes gritadas en múltiples idiomas, el sonido distintivo de granadas flash being preparadas.",
    "—Jung-ho tenía razón. Lo supe desde el primer día que entré al valle, y tardé demasiado en decírselo.",
    "—A mi familia, si están viendo esto: lo siento por no haber podido explicar esto antes. Pero espero que entiendan que esto era más grande que cualquier elección personal.",
    "—A todos los que han seguido MinJung Oscura durante estos años: gracias por acompañarme en esta investigación. Resulta que el misterio más grande era el que estábamos viviendo sin saberlo.",
    "[P100]",
    "Las puertas del centro de transmisión explotaron hacia adentro. Soldados de múltiples nacionalidades entraron simultáneamente, armas levantadas, gritando órdenes contradictorias en diferentes idiomas.",
    "—¡Manos arriba! ¡Aléjese del equipo de transmisión!",
    "Maya levantó sus manos lentamente, pero mantuvo su posición frente a la cámara.",
    "—Esta es Maya Park, firmando por última vez desde MinJung Oscura. Recuerden: sin importar lo que elijan, elíjanlo con amor. Por ustedes mismos, por su especie, por las formas de vida que podrían venir después de nosotros.",
    "Un soldado se acercó para desconectar el equipo de transmisión. Maya se interpuso entre él y la cámara.",
    "—Por favor, déjenme terminar. Solo necesito...",
    "El disparo fue instantáneo. No malicioso, no cruel - simplemente el resultado de protocolos militares ejecutados por soldados entrenados para neutralizar amenazas a la seguridad nacional. Maya colapsó, pero su muerte activó un sistema de respaldo que había estado preparando durante días.",
    "Mientras su cuerpo caía, toda la información que había recopilado - archivos, videos, documentos, coordenadas - se transmitió automáticamente a 847 ubicaciones alrededor del mundo. Servidores privados, universidades, organizaciones de noticias, grupos de activistas, incluso sistemas de gobierno que habían sido infiltrados por simpatizantes.",
    "—Si están escuchando esto, significa que he muerto tratando de preservar esta información. No me lloren. Celebren que vivimos en una época donde una persona puede cambiar el mundo simplemente contando la verdad.",
    "La transmisión final de MinJung Oscura había durado exactamente 47 minutos y 23 segundos. Había sido vista por más de 180 millones de personas simultáneamente - una cifra sin precedentes para cualquier transmisión independiente. Y en el momento de la muerte de Maya, se convirtió en el documento más descargado, compartido y traducido en la historia humana."
  ]
};
