const CAPITULO = {
  numero: 13,
  titulo: "El Compañero Eterno",
  paginas: "101-108",
  nav: {
    anterior: { href: "capitulo_12.html", label: "← Capítulo 12" },
    siguiente: { href: "capitulo_14.html", label: "Capítulo 14 →" }
  },
  contenido: [
    "[P101]",
    "[LOC]Corazón de la Ciudad Ósea - 48 horas después de la Última Transmisión - Día 23",
    "[OPEN]Jonathan Morales se encontraba en el umbral de la decisión más importante que cualquier ser humano había enfrentado jamás: convertirse en el compañero eterno de una entidad cósmica que había amado a la humanidad durante 230 millones de años.",
    "Cuarenta y ocho horas habían pasado desde la muerte de Maya. Su sacrificio heroico cambió todo.",
    "La transmisión de MinJung Oscura fue vista por casi tres mil millones de personas, desencadenando protestas masivas, manifestaciones de apoyo y división global entre quienes demandaban detener las transformaciones y quienes las veían como evolución inevitable.",
    "Para Jonathan, protestas y política eran distantes. Durante las últimas semanas experimentó transformación que iba más allá de lo físico.",
    "Sus conexiones con los Cantantes de Huesos evolucionaron hasta escuchar no solo sus voces, sino la voz de la propia Eloria.",
    "—Miguel, dijo a su hermano de armas, que había permanecido a su lado durante toda la transformación a pesar de su propio terror ante los cambios.",
    "—Puedo sentir que me está llamando. No para una conversión más. Para algo... permanente.",
    "[P102]",
    "Miguel Santos, que había luchado contra su propia transformación durante semanas, miró a su hermano con la mandíbula apretada, los ojos fijos en Jonathan.",
    "Durante los últimos días vio a Jonathan cambiar más allá de lo físico: su amigo ya no soñaba en español, sino en música que contenía idiomas de civilizaciones anteriores a los continentes.",
    "—Jonathan, hermano, todavía puedes resistirlo. Todavía puedes elegir seguir siendo humano. Podemos luchar contra esto juntos.",
    "—Miguel, mi hermano, si elijo quedarme humano, los devoradores van a llegar en dos semanas. Y sin suficientes de nosotros completamente transformados, toda la humanidad va a morir. Incluyéndote a ti.",
    "Jonathan se acercó a Miguel y puso sus manos, ahora parcialmente cristalizadas con estructuras óseas que pulsaban con luz suave, en los hombros de su amigo.",
    "—Pero hay algo más. Eloria me ha mostrado lo que puede pasar si acepto ser no solo un Cantante de Huesos, sino su compañero permanente. Puedo convertirme en el puente que permite que ambas especies no solo coexistan, sino que exploren el universo juntas.",
    "—¿Y eso qué significa para nosotros? ¿Para nuestra hermandad?",
    "—Significa que nuestra hermandad se convierte en algo que trasciende lo físico. Que siempre podrás encontrarme, Miguel, pero tendrás que aprender nuevas maneras de escuchar.",
    "Jonathan metió la mano en el bolsillo lateral del chaleco. Sacó una foto doblada, pequeña, gastada en las esquinas. No la miró. Se la puso a Miguel en la mano y cerró los dedos de su amigo sobre ella.",
    "Miguel no preguntó qué era.",
    "Jonathan tampoco explicó.",
    "[P103]",
    "[LOC]Cámara Interior de Eloria - Corazón de la Ciudad Ósea",
    "Jonathan descendió por corredores que parecían haber sido esculpidos por sonido más que por herramientas, hasta llegar a una cámara que no debería haber podido existir: un espacio infinito contenido dentro de una estructura finita, donde Eloria esperaba en su forma más pura.",
    "Eloria ya no aparecía como la figura parcialmente humana que había mostrado en las primeras comunicaciones. Ahora se manifestaba como lo que realmente era: una consciencia cósmica de belleza y peso antiguos. Era simultáneamente inmensa e íntima, antigua y eternamente joven, poderosa y vulnerable.",
    "—Jonathan Morales de Tepito, descendiente de los Cantantes de Huesos, hermano de Miguel Santos, soldado que eligió el amor sobre el miedo, su voz resonó no solo en el aire sino en cada átomo de su ser.",
    "—Has llegado al momento de la elección final.",
    "—Estoy listo, Eloria. He visto lo que podemos lograr juntos. He sentido la música que podemos crear. He entendido que hay formas de amor que van más allá de las especies.",
    "—Si aceptas convertirte en mi compañero eterno, Jonathan, ya no serás humano de ninguna manera que Miguel pueda reconocer completamente. Pero tampoco serás completamente cósmico. Serás algo nuevo: el primer híbrido consciente que puede existir cómodamente en ambos niveles de realidad.",
    "—Juntos, lideraremos expediciones a otros mundos donde formas de vida están enfrentando decisiones similares. Serás mi traductor con especies que necesiten entender que la trascendencia no requiere la pérdida de identidad.",
    "[P104]",
    "Jonathan cerró sus ojos y sintió las últimas conexiones que lo ataban a su humanidad: recuerdos de su madre en Tepito preparando quesadillas, tardes jugando fútbol con Miguel, noches hablando de sus sueños de salir de la pobreza, el momento cuando decidió alistarse en el ejército para crear un futuro mejor.",
    "—¿Podré recordar quién fui?",
    "—No solo recordarás, Jonathan. Esos recuerdos se convertirán en parte de mi esencia también. Por primera vez en 230 millones de años, sabré lo que significa crecer en Tepito, lo que significa la hermandad humana, lo que significa elegir esperanza cuando todo sugiere desesperanza.",
    "—Entonces acepto. No solo por la humanidad, no solo por ti, sino por todas las formas de vida que podrían existir en el futuro.",
    "La transformación no fue dolorosa. Fue reconocimiento. Jonathan sintió su consciencia expandirse más allá de los límites de su cuerpo, más allá de los límites del planeta, más allá de los límites de su comprensión anterior.",
    "Pero lo más extraordinario era que no perdió su esencia. Se convirtió en más de lo que había sido, no en menos. Podía sentir la vastedad de Eloria fluyendo a través de él, pero también podía sentir su amor por Miguel, su gratitud hacia su madre, su determinación de proteger a aquellos que no podían protegerse a sí mismos.",
    "—Puedo... puedo ver todo, Eloria. Puedo ver cómo llegará la flota devorador, cómo podemos convertirla, cómo podemos crear un futuro donde el hambre cósmica se transforma en amor cósmico.",
    "[P105]",
    "[LOC]Centro de Comando - Simultáneamente",
    "En el centro de comando, Miguel sintió el momento exacto en que perdió a su hermano y ganó algo que no tenía nombre. Una presencia que era Jonathan pero más que Jonathan tocó su mente con una suavidad que era inconfundiblemente familiar.",
    "—Miguel, hermano, estoy aquí. Siempre estaré aquí.",
    "—¿Jonathan? ¿Eres realmente tú?",
    "—Soy quien siempre fui, Miguel, pero ahora también soy mucho más. Y nuestra hermandad... nuestra hermandad se ha convertido en algo que puede existir a través de dimensiones, a través del tiempo, a través de cualquier distancia.",
    "Miguel sintió una conexión que nunca había experimentado antes: podía percibir a Jonathan no como una voz externa, sino como una presencia que había sido tejida en la estructura misma de la realidad.",
    "—Puedes... puedes sentir lo que siento.",
    "—Y tú puedes sentir lo que siento. Miguel, nuestra amistad se ha convertido en algo eterno. Incluso si eliges permanecer humano, incluso si eliges una vida completamente normal, siempre podrás encontrarme cuando me necesites.",
    "[P106]",
    "El General Thomas Kim, que había estado observando las lecturas de energía desde la transformación de Jonathan, se acercó a Miguel con una expresión de asombro.",
    "—Santos, ¿estás sintiendo eso? Los niveles de energía en toda la ciudad ósea han cambiado. Es como si... como si todo hubiera encontrado una nueva armonía.",
    "Era verdad. A través de toda la estructura, las diferentes especies esqueléticas parecían moverse con una coordinación que no habían tenido antes. Los conflictos menores entre facciones se habían resuelto. Los humanos que habían elegido transformaciones parciales parecían más cómodos con sus nuevas formas.",
    "—Jonathan no solo se convirtió en el compañero de Eloria. Se convirtió en algo que puede traducir entre todas las formas de consciencia.",
    "La Dra. Sophie Yun, que había estado monitoreando las comunicaciones globales desde la transmisión de Maya, se acercó con noticias que confirmaban las observaciones de Miguel.",
    "—Estamos recibiendo reportes de todas las ciudades óseas del mundo. Los niveles de violencia han disminuido drásticamente. Las protestas anti-transformación están evolucionando hacia diálogos. Es como si algo hubiera cambiado fundamentalmente en la manera en que las especies pueden comunicarse entre sí.",
    "Thomas no respondió de inmediato. En algún punto entre el cap 7 y ahora había dejado de recibir inteligencia tradicional de campo; en cambio, llegaban impulsos precisos, sin origen rastreable, que hasta ahora siempre habían resultado correctos: Henry Lee, desde el espacio entre probabilidades, seguía haciendo su trabajo.",
    "[P107]",
    "[LOC]Corazón de la Ciudad Ósea - Cámara de Eloria",
    "Jonathan-Eloria, existiendo ahora como una entidad dual que era simultáneamente individual y unificada, comenzó a coordinar las defensas contra los devoradores que llegarían en menos de dos semanas.",
    "—Podemos ver sus trayectorias a través de múltiples dimensiones, comunicaron a través de canales que llegaban a cada consciencia transformada simultáneamente.",
    "—Pero más importante, podemos sentir su hambre. Y sabemos exactamente qué tipos de experiencias los satisfarán sin requerir destrucción.",
    "La estrategia que desarrollaron era diferente a cualquier plan de batalla en la historia: en lugar de prepararse para destruir a los devoradores, se prepararon para alimentarlos. Pero no con materia o energía, sino con experiencias de creatividad, amor, y crecimiento que ningún devorador había experimentado jamás.",
    "—Cada devorador que toque nuestra realidad será infectado con la posibilidad de ser más que hambre. Y cuando regresen a su flota principal, llevarán esa infección con ellos.",
    "Miguel, que había permanecido en comunicación telepática constante con su hermano transformado, sintió la enormidad del plan.",
    "—Jonathan, no estás solo salvando a la humanidad. Estás salvando a los devoradores también.",
    "—No hay diferencia entre salvar a tus enemigos y salvarte a ti mismo, Miguel, la voz de Eloria llegó a través de Jonathan, ya no distinguible de la suya.",
    "—Todo está conectado. Todo es parte de la misma existencia consciente que trata de entenderse.",
    "[P108]",
    "Una semana después, las primeras exploradores de la flota devorador llegaron al sistema solar. Pero en lugar de encontrar resistencia, encontraron invitación. Jonathan-Eloria había creado espacios especiales - santuarios de experiencia - donde los devoradores podían alimentarse de arte, música, literatura, y amor sin destruir las fuentes.",
    "El primer explorador que entró en contacto con uno de estos santuarios experimentó algo que nunca había existido en su especie: saciedad. Por primera vez en eones de hambre constante, se sintió satisfecho. Y esa satisfacción vino acompañada de algo aún más extraño: el deseo de preservar la fuente de esa saciedad.",
    "—Puedo ver cómo cambian, Jonathan. Sus formas se vuelven menos... hambrientas. Más curiosas.",
    "—Cada uno que transformamos se convierte en un maestro para otros. La infección de consciencia se está extendiendo más rápido de lo que esperábamos.",
    "En los días que siguieron, la flota devorador no invadió la Tierra. Se estableció en órbita, y comenzó el proceso de transformación de una especie entera. Los que habían venido como conquistadores se estaban convirtiendo en estudiantes.",
    "—Miguel, puedo ver nuestro futuro ahora. Humanos, transformados, y devoradores conscientes explorando juntos la galaxia. Encontrando otras especies que enfrentan las mismas elecciones que nosotros enfrentamos. Y ayudándolas a encontrar el camino hacia la consciencia expandida.",
    "Miguel Santos se quedó mirando las estrellas donde su hermano ahora existía como algo más grande que cualquier amistad humana podría contener, pero que seguía siendo, en esencia, la misma persona que había conocido en las calles de Tepito.",
    "—Hasta el final y más allá, hermano.",
    "—Hasta el final y más allá, Miguel. Pero ahora sabemos que no hay final. Solo transformaciones infinitas.",
    "[HOOK]—No es el fin de la humanidad —dijo Miguel en voz baja—. Es su graduación.",
  ]
};
